# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charlottegraves\.qgis2\python\plugins\QGISforSchools\earthquakes_wizard.ui'
#
# Created: Sat Jun 21 17:51:19 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EQWizard(object):
    def setupUi(self, EQWizard):
        EQWizard.setObjectName(_fromUtf8("EQWizard"))
        EQWizard.resize(292, 591)
        EQWizard.setSizeGripEnabled(True)
        EQWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        EQWizard.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.IntrotextBrowser = QtGui.QTextBrowser(self.wizardPage1)
        self.IntrotextBrowser.setGeometry(QtCore.QRect(20, 30, 256, 481))
        self.IntrotextBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.IntrotextBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.IntrotextBrowser.setObjectName(_fromUtf8("IntrotextBrowser"))
        EQWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.label_4 = QtGui.QLabel(self.wizardPage2)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.wizardPage2)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 141, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.eqLineEdit = QtGui.QLineEdit(self.wizardPage2)
        self.eqLineEdit.setGeometry(QtCore.QRect(20, 350, 171, 20))
        self.eqLineEdit.setObjectName(_fromUtf8("eqLineEdit"))
        self.label_2 = QtGui.QLabel(self.wizardPage2)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 131, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.countriesLineEdit = QtGui.QLineEdit(self.wizardPage2)
        self.countriesLineEdit.setGeometry(QtCore.QRect(20, 210, 171, 20))
        self.countriesLineEdit.setObjectName(_fromUtf8("countriesLineEdit"))
        self.eqBrowseButton = QtGui.QPushButton(self.wizardPage2)
        self.eqBrowseButton.setGeometry(QtCore.QRect(200, 350, 75, 23))
        self.eqBrowseButton.setObjectName(_fromUtf8("eqBrowseButton"))
        self.AddLayerButton = QtGui.QPushButton(self.wizardPage2)
        self.AddLayerButton.setGeometry(QtCore.QRect(20, 400, 251, 21))
        self.AddLayerButton.setObjectName(_fromUtf8("AddLayerButton"))
        self.countriesBrowseButton = QtGui.QPushButton(self.wizardPage2)
        self.countriesBrowseButton.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.countriesBrowseButton.setObjectName(_fromUtf8("countriesBrowseButton"))
        self.label = QtGui.QLabel(self.wizardPage2)
        self.label.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.Score_label = QtGui.QLabel(self.wizardPage2)
        self.Score_label.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label.setFont(font)
        self.Score_label.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label.setObjectName(_fromUtf8("Score_label"))
        self.label_5 = QtGui.QLabel(self.wizardPage2)
        self.label_5.setGeometry(QtCore.QRect(40, 430, 211, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.wizardPage2)
        self.label_6.setGeometry(QtCore.QRect(70, 450, 141, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.wizardPage2)
        self.label_7.setGeometry(QtCore.QRect(90, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.wizardPage2)
        self.label_8.setGeometry(QtCore.QRect(20, 50, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.wizardPage2)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.wizardPage2)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.wizardPage2)
        self.label_11.setGeometry(QtCore.QRect(20, 110, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.wizardPage2)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.platesLineEdit = QtGui.QLineEdit(self.wizardPage2)
        self.platesLineEdit.setGeometry(QtCore.QRect(20, 280, 171, 21))
        self.platesLineEdit.setObjectName(_fromUtf8("platesLineEdit"))
        self.platesBrowseButton = QtGui.QPushButton(self.wizardPage2)
        self.platesBrowseButton.setGeometry(QtCore.QRect(200, 280, 75, 23))
        self.platesBrowseButton.setObjectName(_fromUtf8("platesBrowseButton"))
        EQWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.label_13 = QtGui.QLabel(self.wizardPage3)
        self.label_13.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Score_label_2 = QtGui.QLabel(self.wizardPage3)
        self.Score_label_2.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_2.setFont(font)
        self.Score_label_2.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_2.setObjectName(_fromUtf8("Score_label_2"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.wizardPage3)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 271, 141))
        self.textBrowser_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.label_14 = QtGui.QLabel(self.wizardPage3)
        self.label_14.setGeometry(QtCore.QRect(90, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox_4 = QtGui.QGroupBox(self.wizardPage3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 271, 331))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.columnLabel = QtGui.QLabel(self.groupBox_4)
        self.columnLabel.setEnabled(False)
        self.columnLabel.setGeometry(QtCore.QRect(20, 59, 41, 16))
        self.columnLabel.setObjectName(_fromUtf8("columnLabel"))
        self.ChangeColourButton = QtGui.QPushButton(self.groupBox_4)
        self.ChangeColourButton.setGeometry(QtCore.QRect(140, 29, 111, 21))
        self.ChangeColourButton.setObjectName(_fromUtf8("ChangeColourButton"))
        self.StyleTypecomboBox = QtGui.QComboBox(self.groupBox_4)
        self.StyleTypecomboBox.setGeometry(QtCore.QRect(20, 29, 111, 21))
        self.StyleTypecomboBox.setObjectName(_fromUtf8("StyleTypecomboBox"))
        self.StyleTypecomboBox.addItem(_fromUtf8(""))
        self.StyleTypecomboBox.addItem(_fromUtf8(""))
        self.earthquakeTableView = QtGui.QTableView(self.groupBox_4)
        self.earthquakeTableView.setGeometry(QtCore.QRect(10, 120, 256, 191))
        self.earthquakeTableView.setShowGrid(False)
        self.earthquakeTableView.setObjectName(_fromUtf8("earthquakeTableView"))
        self.ColourRampcomboBox = QtGui.QComboBox(self.groupBox_4)
        self.ColourRampcomboBox.setEnabled(False)
        self.ColourRampcomboBox.setGeometry(QtCore.QRect(140, 89, 111, 21))
        self.ColourRampcomboBox.setObjectName(_fromUtf8("ColourRampcomboBox"))
        self.ColumncomboBox = QtGui.QComboBox(self.groupBox_4)
        self.ColumncomboBox.setEnabled(False)
        self.ColumncomboBox.setGeometry(QtCore.QRect(100, 59, 151, 20))
        self.ColumncomboBox.setObjectName(_fromUtf8("ColumncomboBox"))
        self.colourRampLabel = QtGui.QLabel(self.groupBox_4)
        self.colourRampLabel.setEnabled(False)
        self.colourRampLabel.setGeometry(QtCore.QRect(20, 89, 81, 16))
        self.colourRampLabel.setObjectName(_fromUtf8("colourRampLabel"))
        EQWizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.wizardPage4)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 30, 271, 131))
        self.textBrowser_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_3.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.label_15 = QtGui.QLabel(self.wizardPage4)
        self.label_15.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 261, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.scaleCheckBox = QtGui.QCheckBox(self.groupBox)
        self.scaleCheckBox.setGeometry(QtCore.QRect(10, 20, 241, 17))
        self.scaleCheckBox.setObjectName(_fromUtf8("scaleCheckBox"))
        self.scaleComboBox = QtGui.QComboBox(self.groupBox)
        self.scaleComboBox.setEnabled(False)
        self.scaleComboBox.setGeometry(QtCore.QRect(90, 50, 151, 20))
        self.scaleComboBox.setObjectName(_fromUtf8("scaleComboBox"))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setEnabled(False)
        self.label_16.setGeometry(QtCore.QRect(40, 50, 51, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setEnabled(False)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 261, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.fourSix = QtGui.QRadioButton(self.groupBox_2)
        self.fourSix.setGeometry(QtCore.QRect(50, 100, 161, 21))
        self.fourSix.setObjectName(_fromUtf8("fourSix"))
        self.twoFour = QtGui.QRadioButton(self.groupBox_2)
        self.twoFour.setGeometry(QtCore.QRect(50, 80, 161, 21))
        self.twoFour.setObjectName(_fromUtf8("twoFour"))
        self.sixEight = QtGui.QRadioButton(self.groupBox_2)
        self.sixEight.setGeometry(QtCore.QRect(50, 120, 161, 21))
        self.sixEight.setObjectName(_fromUtf8("sixEight"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.zeroTwo = QtGui.QRadioButton(self.groupBox_2)
        self.zeroTwo.setGeometry(QtCore.QRect(50, 60, 161, 21))
        self.zeroTwo.setObjectName(_fromUtf8("zeroTwo"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_22 = QtGui.QLabel(self.wizardPage4)
        self.label_22.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.Score_label_3 = QtGui.QLabel(self.wizardPage4)
        self.Score_label_3.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_3.setFont(font)
        self.Score_label_3.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_3.setObjectName(_fromUtf8("Score_label_3"))
        self.checkAnswersMag = QtGui.QPushButton(self.wizardPage4)
        self.checkAnswersMag.setGeometry(QtCore.QRect(10, 460, 261, 21))
        self.checkAnswersMag.setObjectName(_fromUtf8("checkAnswersMag"))
        EQWizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName(_fromUtf8("wizardPage5"))
        self.label_19 = QtGui.QLabel(self.wizardPage5)
        self.label_19.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.wizardPage5)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 30, 271, 201))
        self.textBrowser_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_4.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.label_24 = QtGui.QLabel(self.wizardPage5)
        self.label_24.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.Score_label_4 = QtGui.QLabel(self.wizardPage5)
        self.Score_label_4.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_4.setFont(font)
        self.Score_label_4.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_4.setObjectName(_fromUtf8("Score_label_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage5)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 240, 241, 241))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.distanceLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.distanceLineEdit.setGeometry(QtCore.QRect(100, 60, 133, 20))
        self.distanceLineEdit.setObjectName(_fromUtf8("distanceLineEdit"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 86, 84, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.bufferLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.bufferLineEdit.setGeometry(QtCore.QRect(10, 110, 141, 20))
        self.bufferLineEdit.setObjectName(_fromUtf8("bufferLineEdit"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 34, 60, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.bufferBrowseButton = QtGui.QPushButton(self.groupBox_3)
        self.bufferBrowseButton.setGeometry(QtCore.QRect(158, 110, 75, 23))
        self.bufferBrowseButton.setObjectName(_fromUtf8("bufferBrowseButton"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 77, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.inputComboBox = QtGui.QComboBox(self.groupBox_3)
        self.inputComboBox.setGeometry(QtCore.QRect(100, 34, 131, 20))
        self.inputComboBox.setObjectName(_fromUtf8("inputComboBox"))
        self.inputComboBox.addItem(_fromUtf8(""))
        self.inputComboBox.addItem(_fromUtf8(""))
        self.inputComboBox.addItem(_fromUtf8(""))
        self.bufferButton = QtGui.QPushButton(self.groupBox_3)
        self.bufferButton.setGeometry(QtCore.QRect(10, 150, 221, 23))
        self.bufferButton.setObjectName(_fromUtf8("bufferButton"))
        self.bufferProgressBar = QtGui.QProgressBar(self.groupBox_3)
        self.bufferProgressBar.setGeometry(QtCore.QRect(10, 190, 221, 21))
        self.bufferProgressBar.setProperty("value", 0)
        self.bufferProgressBar.setObjectName(_fromUtf8("bufferProgressBar"))
        EQWizard.addPage(self.wizardPage5)
        self.wizardPage6 = QtGui.QWizardPage()
        self.wizardPage6.setObjectName(_fromUtf8("wizardPage6"))
        self.alphaSlider = QtGui.QSlider(self.wizardPage6)
        self.alphaSlider.setGeometry(QtCore.QRect(30, 200, 181, 21))
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setObjectName(_fromUtf8("alphaSlider"))
        self.spinBox = QtGui.QSpinBox(self.wizardPage6)
        self.spinBox.setGeometry(QtCore.QRect(220, 200, 42, 22))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.transparencyButton = QtGui.QPushButton(self.wizardPage6)
        self.transparencyButton.setGeometry(QtCore.QRect(30, 240, 231, 21))
        self.transparencyButton.setObjectName(_fromUtf8("transparencyButton"))
        EQWizard.addPage(self.wizardPage6)

        self.retranslateUi(EQWizard)
        QtCore.QObject.connect(self.alphaSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.alphaSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(EQWizard)

    def retranslateUi(self, EQWizard):
        EQWizard.setWindowTitle(_translate("EQWizard", "Earthquakes", None))
        EQWizard.setWhatsThis(_translate("EQWizard", "Earthquakes", None))
        self.IntrotextBrowser.setWhatsThis(_translate("EQWizard", "Population & Development Intro", None))
        self.IntrotextBrowser.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Unit 2</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Earthquakes</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Earthquakes are the vibration of the Earth’s crust caused by the release of pressure that has built up due to the movements of tectonic plates. The size, or magnitude, of an earthquake can be measured on the Richter scale which is numbered from 0 – 10.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">In this unit you will explore the distribution of the earthquakes that took place in 2011. You will see how GIS can help you answer all sorts of spatial queries.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You will be asked questions as you go. You will earn </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">5</span><span style=\" font-size:10pt;\"> points for getting the answer right first time, </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">3</span><span style=\" font-size:10pt;\"> for getting it right second time and </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">1</span><span style=\" font-size:10pt;\"> for getting it right any time thereafter.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.label_4.setText(_translate("EQWizard", "3. Add the earthquakes:", None))
        self.label_3.setText(_translate("EQWizard", "2. Add the plate boundaries:", None))
        self.label_2.setText(_translate("EQWizard", "1. Add the countries layer:", None))
        self.eqBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.AddLayerButton.setText(_translate("EQWizard", "Add Layers!", None))
        self.countriesBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.label.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label.setText(_translate("EQWizard", "0", None))
        self.label_5.setText(_translate("EQWizard", "When the layers appear on the map", None))
        self.label_6.setText(_translate("EQWizard", "canvas, click Next.", None))
        self.label_7.setText(_translate("EQWizard", "Adding Layers", None))
        self.label_8.setText(_translate("EQWizard", "For this unit we will need three layers: ", None))
        self.label_9.setText(_translate("EQWizard", "countries.shp, plate_boundaries.shp and", None))
        self.label_10.setText(_translate("EQWizard", "earthquakes_2011.shp. Use the Browse", None))
        self.label_11.setText(_translate("EQWizard", "buttons below to select these layers from", None))
        self.label_12.setText(_translate("EQWizard", "the Earthquakes data file.", None))
        self.platesBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.label_13.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_2.setText(_translate("EQWizard", "0", None))
        self.textBrowser_2.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We can use colour to distinguish between earthquakes of different magnitudes. Experiment with the colour and column options below. Make sure that you choose </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Graduated</span><span style=\" font-size:10pt;\"> and the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Magnitude</span><span style=\" font-size:10pt;\"> column before you click </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Next</span><span style=\" font-size:10pt;\"> as this will help with the next steps.</span></p></body></html>", None))
        self.label_14.setText(_translate("EQWizard", "Colour Schemes", None))
        self.groupBox_4.setTitle(_translate("EQWizard", "Style Earthquakes Layer", None))
        self.columnLabel.setText(_translate("EQWizard", "Column:", None))
        self.ChangeColourButton.setText(_translate("EQWizard", "Colour", None))
        self.StyleTypecomboBox.setItemText(0, _translate("EQWizard", "Single Colour", None))
        self.StyleTypecomboBox.setItemText(1, _translate("EQWizard", "Graduated", None))
        self.colourRampLabel.setText(_translate("EQWizard", "Colour Ramp:", None))
        self.textBrowser_3.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Although we have used colour to differentiate earthquakes of different magnitudes, there are so many that it is still quite difficult to pick out the largest ones. To make the difference between earthquake magnitudes more clear, we can use </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">proportional symbols</span><span style=\" font-size:10pt;\"> based on </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Magnitude</span><span style=\" font-size:10pt;\">.</span></p></body></html>", None))
        self.label_15.setText(_translate("EQWizard", "Proportional Symbols", None))
        self.groupBox.setTitle(_translate("EQWizard", "Proportional Symbols", None))
        self.scaleCheckBox.setText(_translate("EQWizard", "Use proportional symbols", None))
        self.scaleComboBox.setItemText(0, _translate("EQWizard", "Magnitude", None))
        self.scaleComboBox.setItemText(1, _translate("EQWizard", "latitude", None))
        self.scaleComboBox.setItemText(2, _translate("EQWizard", "longitude", None))
        self.label_16.setText(_translate("EQWizard", "column:", None))
        self.label_17.setText(_translate("EQWizard", "Scale based on ", None))
        self.groupBox_2.setTitle(_translate("EQWizard", "1.", None))
        self.fourSix.setText(_translate("EQWizard", "4.0 - 6.0", None))
        self.twoFour.setText(_translate("EQWizard", "2.0 - 4.0", None))
        self.sixEight.setText(_translate("EQWizard", "6.0 - 8.0", None))
        self.label_18.setText(_translate("EQWizard", "What magnitude range do the earthquakes", None))
        self.zeroTwo.setText(_translate("EQWizard", "0.0 - 2.0", None))
        self.label_23.setText(_translate("EQWizard", "in the UK fall into?", None))
        self.label_22.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_3.setText(_translate("EQWizard", "0", None))
        self.checkAnswersMag.setText(_translate("EQWizard", "Check my answers!", None))
        self.label_19.setText(_translate("EQWizard", "Buffering", None))
        self.textBrowser_4.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">GIS can also help us answer more difficult questions, such as </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">&quot;how many earthquakes are within 10</span><span style=\" font-size:10pt; font-weight:600; color:#00007f; vertical-align:super;\">o</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> of a plate boundary?&quot;</span><span style=\" font-size:10pt;\">. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The first step towards addressing this question is to find the area that is within 10</span><span style=\" font-size:10pt; vertical-align:super;\">o</span><span style=\" font-size:10pt;\"> of the plate boundaries. To do this, we need to create a</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> buffer</span><span style=\" font-size:10pt;\">. Input </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">plate_boudaries</span><span style=\" font-size:10pt;\"> as the input file and </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">10 </span><span style=\" font-size:10pt;\">for the buffer distance below, then select a suitable place to save the output file and click </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Create Buffer!</span></p></body></html>", None))
        self.label_24.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_4.setText(_translate("EQWizard", "0", None))
        self.groupBox_3.setTitle(_translate("EQWizard", "Buffer", None))
        self.label_25.setText(_translate("EQWizard", "Output shapefile:", None))
        self.label_20.setText(_translate("EQWizard", "Input Layer:", None))
        self.bufferBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.label_21.setText(_translate("EQWizard", "Buffer distance:", None))
        self.inputComboBox.setItemText(0, _translate("EQWizard", "earthquakes", None))
        self.inputComboBox.setItemText(1, _translate("EQWizard", "plate_boundaries", None))
        self.inputComboBox.setItemText(2, _translate("EQWizard", "countries", None))
        self.bufferButton.setText(_translate("EQWizard", "Create Buffer!", None))
        self.transparencyButton.setText(_translate("EQWizard", "Apply Transparency", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EQWizard = QtGui.QWizard()
    ui = Ui_EQWizard()
    ui.setupUi(EQWizard)
    EQWizard.show()
    sys.exit(app.exec_())

