# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charlottegraves\.qgis2\python\plugins\QGISforSchools\earthquakes_wizard.ui'
#
# Created: Mon Jun 23 22:15:26 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EQWizard(object):
    def setupUi(self, EQWizard):
        EQWizard.setObjectName(_fromUtf8("EQWizard"))
        EQWizard.resize(292, 591)
        EQWizard.setSizeGripEnabled(True)
        EQWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        EQWizard.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.IntrotextBrowser = QtGui.QTextBrowser(self.wizardPage1)
        self.IntrotextBrowser.setGeometry(QtCore.QRect(20, 30, 256, 481))
        self.IntrotextBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.IntrotextBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.IntrotextBrowser.setObjectName(_fromUtf8("IntrotextBrowser"))
        EQWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.label_4 = QtGui.QLabel(self.wizardPage2)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 131, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.wizardPage2)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 141, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.eqLineEdit = QtGui.QLineEdit(self.wizardPage2)
        self.eqLineEdit.setGeometry(QtCore.QRect(20, 350, 171, 20))
        self.eqLineEdit.setObjectName(_fromUtf8("eqLineEdit"))
        self.label_2 = QtGui.QLabel(self.wizardPage2)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 131, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.countriesLineEdit = QtGui.QLineEdit(self.wizardPage2)
        self.countriesLineEdit.setGeometry(QtCore.QRect(20, 210, 171, 20))
        self.countriesLineEdit.setObjectName(_fromUtf8("countriesLineEdit"))
        self.eqBrowseButton = QtGui.QPushButton(self.wizardPage2)
        self.eqBrowseButton.setGeometry(QtCore.QRect(200, 350, 75, 23))
        self.eqBrowseButton.setObjectName(_fromUtf8("eqBrowseButton"))
        self.AddLayerButton = QtGui.QPushButton(self.wizardPage2)
        self.AddLayerButton.setGeometry(QtCore.QRect(20, 400, 251, 21))
        self.AddLayerButton.setObjectName(_fromUtf8("AddLayerButton"))
        self.countriesBrowseButton = QtGui.QPushButton(self.wizardPage2)
        self.countriesBrowseButton.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.countriesBrowseButton.setObjectName(_fromUtf8("countriesBrowseButton"))
        self.label = QtGui.QLabel(self.wizardPage2)
        self.label.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.Score_label = QtGui.QLabel(self.wizardPage2)
        self.Score_label.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label.setFont(font)
        self.Score_label.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label.setObjectName(_fromUtf8("Score_label"))
        self.label_5 = QtGui.QLabel(self.wizardPage2)
        self.label_5.setGeometry(QtCore.QRect(40, 430, 211, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.wizardPage2)
        self.label_6.setGeometry(QtCore.QRect(70, 450, 141, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.wizardPage2)
        self.label_7.setGeometry(QtCore.QRect(90, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.wizardPage2)
        self.label_8.setGeometry(QtCore.QRect(20, 50, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.wizardPage2)
        self.label_9.setGeometry(QtCore.QRect(20, 70, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.wizardPage2)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.wizardPage2)
        self.label_11.setGeometry(QtCore.QRect(20, 110, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.wizardPage2)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.platesLineEdit = QtGui.QLineEdit(self.wizardPage2)
        self.platesLineEdit.setGeometry(QtCore.QRect(20, 280, 171, 21))
        self.platesLineEdit.setObjectName(_fromUtf8("platesLineEdit"))
        self.platesBrowseButton = QtGui.QPushButton(self.wizardPage2)
        self.platesBrowseButton.setGeometry(QtCore.QRect(200, 280, 75, 23))
        self.platesBrowseButton.setObjectName(_fromUtf8("platesBrowseButton"))
        EQWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.label_13 = QtGui.QLabel(self.wizardPage3)
        self.label_13.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Score_label_2 = QtGui.QLabel(self.wizardPage3)
        self.Score_label_2.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_2.setFont(font)
        self.Score_label_2.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_2.setObjectName(_fromUtf8("Score_label_2"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.wizardPage3)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 271, 141))
        self.textBrowser_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.label_14 = QtGui.QLabel(self.wizardPage3)
        self.label_14.setGeometry(QtCore.QRect(90, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox_4 = QtGui.QGroupBox(self.wizardPage3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 271, 331))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.columnLabel = QtGui.QLabel(self.groupBox_4)
        self.columnLabel.setEnabled(False)
        self.columnLabel.setGeometry(QtCore.QRect(20, 59, 41, 16))
        self.columnLabel.setObjectName(_fromUtf8("columnLabel"))
        self.ChangeColourButton = QtGui.QPushButton(self.groupBox_4)
        self.ChangeColourButton.setGeometry(QtCore.QRect(140, 29, 111, 21))
        self.ChangeColourButton.setObjectName(_fromUtf8("ChangeColourButton"))
        self.StyleTypecomboBox = QtGui.QComboBox(self.groupBox_4)
        self.StyleTypecomboBox.setGeometry(QtCore.QRect(20, 29, 111, 21))
        self.StyleTypecomboBox.setObjectName(_fromUtf8("StyleTypecomboBox"))
        self.StyleTypecomboBox.addItem(_fromUtf8(""))
        self.StyleTypecomboBox.addItem(_fromUtf8(""))
        self.earthquakeTableView = QtGui.QTableView(self.groupBox_4)
        self.earthquakeTableView.setGeometry(QtCore.QRect(10, 120, 256, 191))
        self.earthquakeTableView.setShowGrid(False)
        self.earthquakeTableView.setObjectName(_fromUtf8("earthquakeTableView"))
        self.ColourRampcomboBox = QtGui.QComboBox(self.groupBox_4)
        self.ColourRampcomboBox.setEnabled(False)
        self.ColourRampcomboBox.setGeometry(QtCore.QRect(140, 89, 111, 21))
        self.ColourRampcomboBox.setObjectName(_fromUtf8("ColourRampcomboBox"))
        self.ColumncomboBox = QtGui.QComboBox(self.groupBox_4)
        self.ColumncomboBox.setEnabled(False)
        self.ColumncomboBox.setGeometry(QtCore.QRect(100, 59, 151, 20))
        self.ColumncomboBox.setObjectName(_fromUtf8("ColumncomboBox"))
        self.colourRampLabel = QtGui.QLabel(self.groupBox_4)
        self.colourRampLabel.setEnabled(False)
        self.colourRampLabel.setGeometry(QtCore.QRect(20, 89, 81, 16))
        self.colourRampLabel.setObjectName(_fromUtf8("colourRampLabel"))
        EQWizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.wizardPage4)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 30, 271, 131))
        self.textBrowser_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_3.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.label_15 = QtGui.QLabel(self.wizardPage4)
        self.label_15.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 261, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.scaleCheckBox = QtGui.QCheckBox(self.groupBox)
        self.scaleCheckBox.setGeometry(QtCore.QRect(10, 20, 241, 17))
        self.scaleCheckBox.setObjectName(_fromUtf8("scaleCheckBox"))
        self.scaleComboBox = QtGui.QComboBox(self.groupBox)
        self.scaleComboBox.setEnabled(False)
        self.scaleComboBox.setGeometry(QtCore.QRect(90, 50, 151, 20))
        self.scaleComboBox.setObjectName(_fromUtf8("scaleComboBox"))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.scaleComboBox.addItem(_fromUtf8(""))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setEnabled(False)
        self.label_16.setGeometry(QtCore.QRect(40, 50, 51, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setEnabled(False)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 261, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.fourSix = QtGui.QRadioButton(self.groupBox_2)
        self.fourSix.setGeometry(QtCore.QRect(50, 100, 161, 21))
        self.fourSix.setObjectName(_fromUtf8("fourSix"))
        self.twoFour = QtGui.QRadioButton(self.groupBox_2)
        self.twoFour.setGeometry(QtCore.QRect(50, 80, 161, 21))
        self.twoFour.setObjectName(_fromUtf8("twoFour"))
        self.sixEight = QtGui.QRadioButton(self.groupBox_2)
        self.sixEight.setGeometry(QtCore.QRect(50, 120, 161, 21))
        self.sixEight.setObjectName(_fromUtf8("sixEight"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.zeroTwo = QtGui.QRadioButton(self.groupBox_2)
        self.zeroTwo.setGeometry(QtCore.QRect(50, 60, 161, 21))
        self.zeroTwo.setObjectName(_fromUtf8("zeroTwo"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_22 = QtGui.QLabel(self.wizardPage4)
        self.label_22.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.Score_label_3 = QtGui.QLabel(self.wizardPage4)
        self.Score_label_3.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_3.setFont(font)
        self.Score_label_3.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_3.setObjectName(_fromUtf8("Score_label_3"))
        self.checkAnswersMag = QtGui.QPushButton(self.wizardPage4)
        self.checkAnswersMag.setGeometry(QtCore.QRect(10, 460, 261, 21))
        self.checkAnswersMag.setObjectName(_fromUtf8("checkAnswersMag"))
        EQWizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName(_fromUtf8("wizardPage5"))
        self.label_19 = QtGui.QLabel(self.wizardPage5)
        self.label_19.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.wizardPage5)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 30, 271, 201))
        self.textBrowser_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_4.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.label_24 = QtGui.QLabel(self.wizardPage5)
        self.label_24.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.Score_label_4 = QtGui.QLabel(self.wizardPage5)
        self.Score_label_4.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_4.setFont(font)
        self.Score_label_4.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_4.setObjectName(_fromUtf8("Score_label_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage5)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 240, 261, 191))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.distanceLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.distanceLineEdit.setGeometry(QtCore.QRect(100, 60, 133, 20))
        self.distanceLineEdit.setObjectName(_fromUtf8("distanceLineEdit"))
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 86, 84, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.bufferLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.bufferLineEdit.setGeometry(QtCore.QRect(10, 110, 141, 20))
        self.bufferLineEdit.setObjectName(_fromUtf8("bufferLineEdit"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 34, 60, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.bufferBrowseButton = QtGui.QPushButton(self.groupBox_3)
        self.bufferBrowseButton.setGeometry(QtCore.QRect(158, 110, 75, 23))
        self.bufferBrowseButton.setObjectName(_fromUtf8("bufferBrowseButton"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 77, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.inputComboBox = QtGui.QComboBox(self.groupBox_3)
        self.inputComboBox.setGeometry(QtCore.QRect(100, 34, 131, 20))
        self.inputComboBox.setObjectName(_fromUtf8("inputComboBox"))
        self.inputComboBox.addItem(_fromUtf8(""))
        self.inputComboBox.addItem(_fromUtf8(""))
        self.inputComboBox.addItem(_fromUtf8(""))
        self.bufferButton = QtGui.QPushButton(self.groupBox_3)
        self.bufferButton.setGeometry(QtCore.QRect(10, 150, 221, 23))
        self.bufferButton.setObjectName(_fromUtf8("bufferButton"))
        EQWizard.addPage(self.wizardPage5)
        self.wizardPage6 = QtGui.QWizardPage()
        self.wizardPage6.setObjectName(_fromUtf8("wizardPage6"))
        self.textBrowser_5 = QtGui.QTextBrowser(self.wizardPage6)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 40, 271, 121))
        self.textBrowser_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_5.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.label_26 = QtGui.QLabel(self.wizardPage6)
        self.label_26.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.wizardPage6)
        self.label_27.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.Score_label_5 = QtGui.QLabel(self.wizardPage6)
        self.Score_label_5.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_5.setFont(font)
        self.Score_label_5.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_5.setObjectName(_fromUtf8("Score_label_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.wizardPage6)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 140, 271, 151))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.transparencyButton = QtGui.QPushButton(self.groupBox_5)
        self.transparencyButton.setGeometry(QtCore.QRect(50, 110, 151, 21))
        self.transparencyButton.setObjectName(_fromUtf8("transparencyButton"))
        self.bufferColourButton = QtGui.QPushButton(self.groupBox_5)
        self.bufferColourButton.setGeometry(QtCore.QRect(110, 20, 91, 21))
        self.bufferColourButton.setObjectName(_fromUtf8("bufferColourButton"))
        self.alphaSlider = QtGui.QSlider(self.groupBox_5)
        self.alphaSlider.setGeometry(QtCore.QRect(20, 80, 181, 21))
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setObjectName(_fromUtf8("alphaSlider"))
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 85, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.alphaSpinBox = QtGui.QSpinBox(self.groupBox_5)
        self.alphaSpinBox.setGeometry(QtCore.QRect(210, 80, 41, 21))
        self.alphaSpinBox.setObjectName(_fromUtf8("alphaSpinBox"))
        self.label_30 = QtGui.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(10, 50, 85, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.groupBox_6 = QtGui.QGroupBox(self.wizardPage6)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 310, 271, 151))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.arcticCircle = QtGui.QRadioButton(self.groupBox_6)
        self.arcticCircle.setGeometry(QtCore.QRect(10, 100, 231, 21))
        self.arcticCircle.setObjectName(_fromUtf8("arcticCircle"))
        self.plates = QtGui.QRadioButton(self.groupBox_6)
        self.plates.setGeometry(QtCore.QRect(10, 80, 241, 21))
        self.plates.setObjectName(_fromUtf8("plates"))
        self.equator = QtGui.QRadioButton(self.groupBox_6)
        self.equator.setGeometry(QtCore.QRect(10, 120, 221, 21))
        self.equator.setObjectName(_fromUtf8("equator"))
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.even = QtGui.QRadioButton(self.groupBox_6)
        self.even.setGeometry(QtCore.QRect(10, 60, 241, 21))
        self.even.setObjectName(_fromUtf8("even"))
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        self.label_31.setGeometry(QtCore.QRect(10, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.checkAnswersDist = QtGui.QPushButton(self.wizardPage6)
        self.checkAnswersDist.setGeometry(QtCore.QRect(10, 470, 271, 21))
        self.checkAnswersDist.setObjectName(_fromUtf8("checkAnswersDist"))
        EQWizard.addPage(self.wizardPage6)
        self.wizardPage7 = QtGui.QWizardPage()
        self.wizardPage7.setObjectName(_fromUtf8("wizardPage7"))
        self.textBrowser_6 = QtGui.QTextBrowser(self.wizardPage7)
        self.textBrowser_6.setGeometry(QtCore.QRect(10, 40, 271, 201))
        self.textBrowser_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_6.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.label_32 = QtGui.QLabel(self.wizardPage7)
        self.label_32.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.newLayergroupBox = QtGui.QGroupBox(self.wizardPage7)
        self.newLayergroupBox.setGeometry(QtCore.QRect(20, 340, 241, 101))
        self.newLayergroupBox.setObjectName(_fromUtf8("newLayergroupBox"))
        self.newLayercheckBox = QtGui.QCheckBox(self.newLayergroupBox)
        self.newLayercheckBox.setGeometry(QtCore.QRect(10, 30, 241, 17))
        self.newLayercheckBox.setObjectName(_fromUtf8("newLayercheckBox"))
        self.queryLineEdit = QtGui.QLineEdit(self.newLayergroupBox)
        self.queryLineEdit.setEnabled(False)
        self.queryLineEdit.setGeometry(QtCore.QRect(10, 60, 131, 21))
        self.queryLineEdit.setObjectName(_fromUtf8("queryLineEdit"))
        self.queryBrowseButton = QtGui.QPushButton(self.newLayergroupBox)
        self.queryBrowseButton.setEnabled(False)
        self.queryBrowseButton.setGeometry(QtCore.QRect(150, 60, 75, 23))
        self.queryBrowseButton.setObjectName(_fromUtf8("queryBrowseButton"))
        self.label_33 = QtGui.QLabel(self.wizardPage7)
        self.label_33.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.Score_label_6 = QtGui.QLabel(self.wizardPage7)
        self.Score_label_6.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_6.setFont(font)
        self.Score_label_6.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_6.setObjectName(_fromUtf8("Score_label_6"))
        self.clearSelection = QtGui.QPushButton(self.wizardPage7)
        self.clearSelection.setGeometry(QtCore.QRect(30, 450, 101, 21))
        self.clearSelection.setObjectName(_fromUtf8("clearSelection"))
        self.runQuery = QtGui.QPushButton(self.wizardPage7)
        self.runQuery.setGeometry(QtCore.QRect(150, 450, 101, 21))
        self.runQuery.setObjectName(_fromUtf8("runQuery"))
        self.inputComboBox_2 = QtGui.QComboBox(self.wizardPage7)
        self.inputComboBox_2.setGeometry(QtCore.QRect(140, 240, 111, 21))
        self.inputComboBox_2.setObjectName(_fromUtf8("inputComboBox_2"))
        self.refComboBox = QtGui.QComboBox(self.wizardPage7)
        self.refComboBox.setGeometry(QtCore.QRect(140, 270, 111, 21))
        self.refComboBox.setObjectName(_fromUtf8("refComboBox"))
        self.queryComboBox = QtGui.QComboBox(self.wizardPage7)
        self.queryComboBox.setGeometry(QtCore.QRect(140, 300, 111, 21))
        self.queryComboBox.setObjectName(_fromUtf8("queryComboBox"))
        self.label_34 = QtGui.QLabel(self.wizardPage7)
        self.label_34.setGeometry(QtCore.QRect(20, 240, 121, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.wizardPage7)
        self.label_35.setGeometry(QtCore.QRect(30, 270, 121, 21))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.wizardPage7)
        self.label_36.setGeometry(QtCore.QRect(10, 300, 131, 21))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.wizardPage7)
        self.label_37.setGeometry(QtCore.QRect(160, 320, 101, 21))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.queryProgBar = QtGui.QProgressBar(self.wizardPage7)
        self.queryProgBar.setGeometry(QtCore.QRect(30, 480, 231, 16))
        self.queryProgBar.setProperty("value", 0)
        self.queryProgBar.setObjectName(_fromUtf8("queryProgBar"))
        EQWizard.addPage(self.wizardPage7)
        self.wizardPage8 = QtGui.QWizardPage()
        self.wizardPage8.setObjectName(_fromUtf8("wizardPage8"))
        self.Score_label_7 = QtGui.QLabel(self.wizardPage8)
        self.Score_label_7.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_7.setFont(font)
        self.Score_label_7.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_7.setObjectName(_fromUtf8("Score_label_7"))
        self.label_38 = QtGui.QLabel(self.wizardPage8)
        self.label_38.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.textBrowser_7 = QtGui.QTextBrowser(self.wizardPage8)
        self.textBrowser_7.setGeometry(QtCore.QRect(10, 30, 271, 131))
        self.textBrowser_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_7.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_7.setObjectName(_fromUtf8("textBrowser_7"))
        self.label_39 = QtGui.QLabel(self.wizardPage8)
        self.label_39.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.attribTableView = QtGui.QTableView(self.wizardPage8)
        self.attribTableView.setGeometry(QtCore.QRect(20, 190, 256, 181))
        self.attribTableView.setObjectName(_fromUtf8("attribTableView"))
        self.checkAnswersNum = QtGui.QPushButton(self.wizardPage8)
        self.checkAnswersNum.setGeometry(QtCore.QRect(20, 480, 251, 21))
        self.checkAnswersNum.setObjectName(_fromUtf8("checkAnswersNum"))
        self.groupBox_7 = QtGui.QGroupBox(self.wizardPage8)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 380, 251, 91))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_41 = QtGui.QLabel(self.groupBox_7)
        self.label_41.setGeometry(QtCore.QRect(10, 10, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(10, 30, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.numSpinBox = QtGui.QSpinBox(self.groupBox_7)
        self.numSpinBox.setGeometry(QtCore.QRect(80, 60, 81, 20))
        self.numSpinBox.setMaximum(100000)
        self.numSpinBox.setObjectName(_fromUtf8("numSpinBox"))
        self.lyrComboBox = QtGui.QComboBox(self.wizardPage8)
        self.lyrComboBox.setGeometry(QtCore.QRect(140, 160, 131, 21))
        self.lyrComboBox.setObjectName(_fromUtf8("lyrComboBox"))
        self.label_40 = QtGui.QLabel(self.wizardPage8)
        self.label_40.setGeometry(QtCore.QRect(90, 160, 46, 13))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        EQWizard.addPage(self.wizardPage8)
        self.wizardPage9 = QtGui.QWizardPage()
        self.wizardPage9.setObjectName(_fromUtf8("wizardPage9"))
        self.groupBox_8 = QtGui.QGroupBox(self.wizardPage9)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 100, 271, 161))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.settlement = QtGui.QRadioButton(self.groupBox_8)
        self.settlement.setGeometry(QtCore.QRect(10, 100, 251, 21))
        self.settlement.setObjectName(_fromUtf8("settlement"))
        self.focus = QtGui.QRadioButton(self.groupBox_8)
        self.focus.setGeometry(QtCore.QRect(10, 70, 261, 21))
        self.focus.setObjectName(_fromUtf8("focus"))
        self.epicentre = QtGui.QRadioButton(self.groupBox_8)
        self.epicentre.setGeometry(QtCore.QRect(10, 120, 261, 21))
        self.epicentre.setObjectName(_fromUtf8("epicentre"))
        self.label_43 = QtGui.QLabel(self.groupBox_8)
        self.label_43.setGeometry(QtCore.QRect(10, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.eR = QtGui.QRadioButton(self.groupBox_8)
        self.eR.setGeometry(QtCore.QRect(10, 50, 191, 21))
        self.eR.setObjectName(_fromUtf8("eR"))
        self.label_49 = QtGui.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(30, 130, 221, 20))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.groupBox_8)
        self.label_50.setGeometry(QtCore.QRect(30, 80, 51, 20))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.groupBox_9 = QtGui.QGroupBox(self.wizardPage9)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 270, 271, 191))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.cities = QtGui.QRadioButton(self.groupBox_9)
        self.cities.setGeometry(QtCore.QRect(10, 160, 251, 21))
        self.cities.setObjectName(_fromUtf8("cities"))
        self.plateMovement = QtGui.QRadioButton(self.groupBox_9)
        self.plateMovement.setGeometry(QtCore.QRect(10, 60, 261, 21))
        self.plateMovement.setObjectName(_fromUtf8("plateMovement"))
        self.climate = QtGui.QRadioButton(self.groupBox_9)
        self.climate.setGeometry(QtCore.QRect(10, 120, 261, 21))
        self.climate.setObjectName(_fromUtf8("climate"))
        self.label_44 = QtGui.QLabel(self.groupBox_9)
        self.label_44.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.mining = QtGui.QRadioButton(self.groupBox_9)
        self.mining.setGeometry(QtCore.QRect(10, 90, 251, 21))
        self.mining.setObjectName(_fromUtf8("mining"))
        self.label_45 = QtGui.QLabel(self.groupBox_9)
        self.label_45.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_51 = QtGui.QLabel(self.groupBox_9)
        self.label_51.setGeometry(QtCore.QRect(30, 70, 221, 20))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.groupBox_9)
        self.label_52.setGeometry(QtCore.QRect(30, 100, 221, 20))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_53 = QtGui.QLabel(self.groupBox_9)
        self.label_53.setGeometry(QtCore.QRect(30, 130, 221, 20))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_46 = QtGui.QLabel(self.wizardPage9)
        self.label_46.setGeometry(QtCore.QRect(70, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.wizardPage9)
        self.label_47.setGeometry(QtCore.QRect(20, 40, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.Score_label_8 = QtGui.QLabel(self.wizardPage9)
        self.Score_label_8.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_8.setFont(font)
        self.Score_label_8.setFrameShape(QtGui.QFrame.Box)
        self.Score_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_8.setObjectName(_fromUtf8("Score_label_8"))
        self.label_48 = QtGui.QLabel(self.wizardPage9)
        self.label_48.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.checkAnswersEQ = QtGui.QPushButton(self.wizardPage9)
        self.checkAnswersEQ.setGeometry(QtCore.QRect(20, 480, 251, 21))
        self.checkAnswersEQ.setObjectName(_fromUtf8("checkAnswersEQ"))
        self.label_54 = QtGui.QLabel(self.wizardPage9)
        self.label_54.setGeometry(QtCore.QRect(20, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        EQWizard.addPage(self.wizardPage9)
        self.wizardPage10 = QtGui.QWizardPage()
        self.wizardPage10.setObjectName(_fromUtf8("wizardPage10"))
        self.groupBox_10 = QtGui.QGroupBox(self.wizardPage10)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 160, 271, 121))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.lyrCheckBox = QtGui.QCheckBox(self.groupBox_10)
        self.lyrCheckBox.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.lyrCheckBox.setChecked(True)
        self.lyrCheckBox.setObjectName(_fromUtf8("lyrCheckBox"))
        self.lyrCheckBox_2 = QtGui.QCheckBox(self.groupBox_10)
        self.lyrCheckBox_2.setGeometry(QtCore.QRect(10, 60, 121, 17))
        self.lyrCheckBox_2.setChecked(True)
        self.lyrCheckBox_2.setObjectName(_fromUtf8("lyrCheckBox_2"))
        self.lyrCheckBox_3 = QtGui.QCheckBox(self.groupBox_10)
        self.lyrCheckBox_3.setGeometry(QtCore.QRect(10, 90, 121, 17))
        self.lyrCheckBox_3.setChecked(True)
        self.lyrCheckBox_3.setObjectName(_fromUtf8("lyrCheckBox_3"))
        self.lyrCheckBox_4 = QtGui.QCheckBox(self.groupBox_10)
        self.lyrCheckBox_4.setGeometry(QtCore.QRect(140, 30, 111, 17))
        self.lyrCheckBox_4.setChecked(True)
        self.lyrCheckBox_4.setObjectName(_fromUtf8("lyrCheckBox_4"))
        self.lyrCheckBox_5 = QtGui.QCheckBox(self.groupBox_10)
        self.lyrCheckBox_5.setGeometry(QtCore.QRect(140, 60, 111, 17))
        self.lyrCheckBox_5.setChecked(True)
        self.lyrCheckBox_5.setObjectName(_fromUtf8("lyrCheckBox_5"))
        self.Score_label_9 = QtGui.QLabel(self.wizardPage10)
        self.Score_label_9.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_9.setFont(font)
        self.Score_label_9.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_9.setObjectName(_fromUtf8("Score_label_9"))
        self.label_59 = QtGui.QLabel(self.wizardPage10)
        self.label_59.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.textBrowser_8 = QtGui.QTextBrowser(self.wizardPage10)
        self.textBrowser_8.setGeometry(QtCore.QRect(10, 30, 271, 131))
        self.textBrowser_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_8.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_8.setObjectName(_fromUtf8("textBrowser_8"))
        self.label_60 = QtGui.QLabel(self.wizardPage10)
        self.label_60.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.groupBox_11 = QtGui.QGroupBox(self.wizardPage10)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 290, 271, 161))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.fire = QtGui.QRadioButton(self.groupBox_11)
        self.fire.setGeometry(QtCore.QRect(40, 120, 171, 21))
        self.fire.setObjectName(_fromUtf8("fire"))
        self.shake = QtGui.QRadioButton(self.groupBox_11)
        self.shake.setGeometry(QtCore.QRect(40, 60, 201, 21))
        self.shake.setObjectName(_fromUtf8("shake"))
        self.income = QtGui.QRadioButton(self.groupBox_11)
        self.income.setGeometry(QtCore.QRect(40, 100, 201, 21))
        self.income.setObjectName(_fromUtf8("income"))
        self.label_61 = QtGui.QLabel(self.groupBox_11)
        self.label_61.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.disease = QtGui.QRadioButton(self.groupBox_11)
        self.disease.setGeometry(QtCore.QRect(40, 80, 181, 21))
        self.disease.setObjectName(_fromUtf8("disease"))
        self.label_62 = QtGui.QLabel(self.groupBox_11)
        self.label_62.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.checkAnswersEffects = QtGui.QPushButton(self.wizardPage10)
        self.checkAnswersEffects.setGeometry(QtCore.QRect(20, 460, 251, 21))
        self.checkAnswersEffects.setObjectName(_fromUtf8("checkAnswersEffects"))
        EQWizard.addPage(self.wizardPage10)
        self.wizardPage11 = QtGui.QWizardPage()
        self.wizardPage11.setObjectName(_fromUtf8("wizardPage11"))
        self.Score_label_10 = QtGui.QLabel(self.wizardPage11)
        self.Score_label_10.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_10.setFont(font)
        self.Score_label_10.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_10.setObjectName(_fromUtf8("Score_label_10"))
        self.label_63 = QtGui.QLabel(self.wizardPage11)
        self.label_63.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.wizardPage11)
        self.label_64.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.textBrowser = QtGui.QTextBrowser(self.wizardPage11)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 256, 201))
        self.textBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.groupBox_12 = QtGui.QGroupBox(self.wizardPage11)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 300, 271, 201))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.distanceLineEdit_2 = QtGui.QLineEdit(self.groupBox_12)
        self.distanceLineEdit_2.setGeometry(QtCore.QRect(110, 80, 133, 20))
        self.distanceLineEdit_2.setObjectName(_fromUtf8("distanceLineEdit_2"))
        self.label_56 = QtGui.QLabel(self.groupBox_12)
        self.label_56.setGeometry(QtCore.QRect(20, 110, 84, 16))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.bufferLineEdit_2 = QtGui.QLineEdit(self.groupBox_12)
        self.bufferLineEdit_2.setGeometry(QtCore.QRect(20, 130, 141, 20))
        self.bufferLineEdit_2.setObjectName(_fromUtf8("bufferLineEdit_2"))
        self.label_57 = QtGui.QLabel(self.groupBox_12)
        self.label_57.setGeometry(QtCore.QRect(20, 50, 60, 16))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.bufferBrowseButton_2 = QtGui.QPushButton(self.groupBox_12)
        self.bufferBrowseButton_2.setGeometry(QtCore.QRect(170, 130, 75, 23))
        self.bufferBrowseButton_2.setObjectName(_fromUtf8("bufferBrowseButton_2"))
        self.label_58 = QtGui.QLabel(self.groupBox_12)
        self.label_58.setGeometry(QtCore.QRect(20, 80, 77, 16))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.inputComboBox_3 = QtGui.QComboBox(self.groupBox_12)
        self.inputComboBox_3.setGeometry(QtCore.QRect(110, 50, 131, 20))
        self.inputComboBox_3.setObjectName(_fromUtf8("inputComboBox_3"))
        self.inputComboBox_3.addItem(_fromUtf8(""))
        self.inputComboBox_3.addItem(_fromUtf8(""))
        self.inputComboBox_3.addItem(_fromUtf8(""))
        self.bufferButton_2 = QtGui.QPushButton(self.groupBox_12)
        self.bufferButton_2.setGeometry(QtCore.QRect(20, 160, 221, 23))
        self.bufferButton_2.setObjectName(_fromUtf8("bufferButton_2"))
        self.label_65 = QtGui.QLabel(self.groupBox_12)
        self.label_65.setGeometry(QtCore.QRect(10, 20, 261, 21))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.groupBox_13 = QtGui.QGroupBox(self.wizardPage11)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 200, 271, 91))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.equatorBrowseButton = QtGui.QPushButton(self.groupBox_13)
        self.equatorBrowseButton.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.equatorBrowseButton.setObjectName(_fromUtf8("equatorBrowseButton"))
        self.equatorLineEdit = QtGui.QLineEdit(self.groupBox_13)
        self.equatorLineEdit.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.equatorLineEdit.setText(_fromUtf8(""))
        self.equatorLineEdit.setObjectName(_fromUtf8("equatorLineEdit"))
        self.AddLayerButton_2 = QtGui.QPushButton(self.groupBox_13)
        self.AddLayerButton_2.setGeometry(QtCore.QRect(10, 60, 251, 21))
        self.AddLayerButton_2.setObjectName(_fromUtf8("AddLayerButton_2"))
        EQWizard.addPage(self.wizardPage11)
        self.wizardPage12 = QtGui.QWizardPage()
        self.wizardPage12.setObjectName(_fromUtf8("wizardPage12"))
        self.label_55 = QtGui.QLabel(self.wizardPage12)
        self.label_55.setGeometry(QtCore.QRect(20, 250, 131, 21))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_66 = QtGui.QLabel(self.wizardPage12)
        self.label_66.setGeometry(QtCore.QRect(170, 270, 101, 21))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.queryProgBar_2 = QtGui.QProgressBar(self.wizardPage12)
        self.queryProgBar_2.setGeometry(QtCore.QRect(40, 430, 231, 16))
        self.queryProgBar_2.setProperty("value", 0)
        self.queryProgBar_2.setObjectName(_fromUtf8("queryProgBar_2"))
        self.runQuery_2 = QtGui.QPushButton(self.wizardPage12)
        self.runQuery_2.setGeometry(QtCore.QRect(160, 400, 101, 21))
        self.runQuery_2.setObjectName(_fromUtf8("runQuery_2"))
        self.newLayergroupBox_2 = QtGui.QGroupBox(self.wizardPage12)
        self.newLayergroupBox_2.setGeometry(QtCore.QRect(30, 290, 241, 101))
        self.newLayergroupBox_2.setObjectName(_fromUtf8("newLayergroupBox_2"))
        self.newLayercheckBox_2 = QtGui.QCheckBox(self.newLayergroupBox_2)
        self.newLayercheckBox_2.setGeometry(QtCore.QRect(10, 30, 241, 17))
        self.newLayercheckBox_2.setObjectName(_fromUtf8("newLayercheckBox_2"))
        self.queryLineEdit_2 = QtGui.QLineEdit(self.newLayergroupBox_2)
        self.queryLineEdit_2.setEnabled(False)
        self.queryLineEdit_2.setGeometry(QtCore.QRect(10, 60, 131, 21))
        self.queryLineEdit_2.setObjectName(_fromUtf8("queryLineEdit_2"))
        self.queryBrowseButton_2 = QtGui.QPushButton(self.newLayergroupBox_2)
        self.queryBrowseButton_2.setEnabled(False)
        self.queryBrowseButton_2.setGeometry(QtCore.QRect(150, 60, 75, 23))
        self.queryBrowseButton_2.setObjectName(_fromUtf8("queryBrowseButton_2"))
        self.label_67 = QtGui.QLabel(self.wizardPage12)
        self.label_67.setGeometry(QtCore.QRect(40, 220, 121, 21))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.label_68 = QtGui.QLabel(self.wizardPage12)
        self.label_68.setGeometry(QtCore.QRect(30, 190, 121, 21))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.clearSelection_2 = QtGui.QPushButton(self.wizardPage12)
        self.clearSelection_2.setGeometry(QtCore.QRect(40, 400, 101, 21))
        self.clearSelection_2.setObjectName(_fromUtf8("clearSelection_2"))
        self.queryComboBox_2 = QtGui.QComboBox(self.wizardPage12)
        self.queryComboBox_2.setGeometry(QtCore.QRect(150, 250, 111, 21))
        self.queryComboBox_2.setObjectName(_fromUtf8("queryComboBox_2"))
        self.inputComboBox_4 = QtGui.QComboBox(self.wizardPage12)
        self.inputComboBox_4.setGeometry(QtCore.QRect(150, 190, 111, 21))
        self.inputComboBox_4.setObjectName(_fromUtf8("inputComboBox_4"))
        self.refComboBox_2 = QtGui.QComboBox(self.wizardPage12)
        self.refComboBox_2.setGeometry(QtCore.QRect(150, 220, 111, 21))
        self.refComboBox_2.setObjectName(_fromUtf8("refComboBox_2"))
        self.label_69 = QtGui.QLabel(self.wizardPage12)
        self.label_69.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.Score_label_11 = QtGui.QLabel(self.wizardPage12)
        self.Score_label_11.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_11.setFont(font)
        self.Score_label_11.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_11.setObjectName(_fromUtf8("Score_label_11"))
        self.label_70 = QtGui.QLabel(self.wizardPage12)
        self.label_70.setGeometry(QtCore.QRect(70, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.textBrowser_9 = QtGui.QTextBrowser(self.wizardPage12)
        self.textBrowser_9.setGeometry(QtCore.QRect(20, 40, 256, 111))
        self.textBrowser_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_9.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_9.setObjectName(_fromUtf8("textBrowser_9"))
        EQWizard.addPage(self.wizardPage12)
        self.wizardPage13 = QtGui.QWizardPage()
        self.wizardPage13.setObjectName(_fromUtf8("wizardPage13"))
        self.label_71 = QtGui.QLabel(self.wizardPage13)
        self.label_71.setGeometry(QtCore.QRect(90, 130, 46, 13))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.attribTableView_2 = QtGui.QTableView(self.wizardPage13)
        self.attribTableView_2.setGeometry(QtCore.QRect(20, 160, 256, 181))
        self.attribTableView_2.setObjectName(_fromUtf8("attribTableView_2"))
        self.checkAnswersNum_2 = QtGui.QPushButton(self.wizardPage13)
        self.checkAnswersNum_2.setGeometry(QtCore.QRect(20, 480, 251, 21))
        self.checkAnswersNum_2.setObjectName(_fromUtf8("checkAnswersNum_2"))
        self.label_72 = QtGui.QLabel(self.wizardPage13)
        self.label_72.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.groupBox_14 = QtGui.QGroupBox(self.wizardPage13)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 350, 251, 121))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.label_73 = QtGui.QLabel(self.groupBox_14)
        self.label_73.setGeometry(QtCore.QRect(10, 10, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_74 = QtGui.QLabel(self.groupBox_14)
        self.label_74.setGeometry(QtCore.QRect(10, 30, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.numSpinBox_2 = QtGui.QSpinBox(self.groupBox_14)
        self.numSpinBox_2.setGeometry(QtCore.QRect(80, 80, 81, 20))
        self.numSpinBox_2.setMaximum(100000)
        self.numSpinBox_2.setObjectName(_fromUtf8("numSpinBox_2"))
        self.label_76 = QtGui.QLabel(self.groupBox_14)
        self.label_76.setGeometry(QtCore.QRect(10, 50, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.textBrowser_10 = QtGui.QTextBrowser(self.wizardPage13)
        self.textBrowser_10.setGeometry(QtCore.QRect(10, 30, 271, 91))
        self.textBrowser_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_10.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_10.setObjectName(_fromUtf8("textBrowser_10"))
        self.lyrComboBox_2 = QtGui.QComboBox(self.wizardPage13)
        self.lyrComboBox_2.setGeometry(QtCore.QRect(140, 130, 131, 21))
        self.lyrComboBox_2.setObjectName(_fromUtf8("lyrComboBox_2"))
        self.Score_label_12 = QtGui.QLabel(self.wizardPage13)
        self.Score_label_12.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_12.setFont(font)
        self.Score_label_12.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_12.setObjectName(_fromUtf8("Score_label_12"))
        self.label_75 = QtGui.QLabel(self.wizardPage13)
        self.label_75.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        EQWizard.addPage(self.wizardPage13)

        self.retranslateUi(EQWizard)
        QtCore.QObject.connect(self.alphaSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.alphaSpinBox.setValue)
        QtCore.QObject.connect(self.alphaSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.alphaSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(EQWizard)

    def retranslateUi(self, EQWizard):
        EQWizard.setWindowTitle(_translate("EQWizard", "Earthquakes", None))
        EQWizard.setWhatsThis(_translate("EQWizard", "Earthquakes", None))
        self.IntrotextBrowser.setWhatsThis(_translate("EQWizard", "Population & Development Intro", None))
        self.IntrotextBrowser.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Unit 2</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Earthquakes</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Earthquakes are the vibration of the Earth’s crust caused by the release of pressure that has built up due to the movements of tectonic plates. The size, or magnitude, of an earthquake can be measured on the Richter scale which is numbered from 0 – 10.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">In this unit you will explore the distribution of the earthquakes that took place in 2011. You will see how GIS can help you answer all sorts of spatial queries and questions.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You will be asked questions as you go. You will earn </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">5</span><span style=\" font-size:10pt;\"> points for getting the answer right first time, </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">3</span><span style=\" font-size:10pt;\"> for getting it right second time and </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">1</span><span style=\" font-size:10pt;\"> for getting it right any time thereafter.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.label_4.setText(_translate("EQWizard", "3. Add the earthquakes:", None))
        self.label_3.setText(_translate("EQWizard", "2. Add the plate boundaries:", None))
        self.label_2.setText(_translate("EQWizard", "1. Add the countries layer:", None))
        self.eqBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.AddLayerButton.setText(_translate("EQWizard", "Add Layers!", None))
        self.countriesBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.label.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label.setText(_translate("EQWizard", "0", None))
        self.label_5.setText(_translate("EQWizard", "When the layers appear on the map", None))
        self.label_6.setText(_translate("EQWizard", "canvas, click Next.", None))
        self.label_7.setText(_translate("EQWizard", "Adding Layers", None))
        self.label_8.setText(_translate("EQWizard", "For this unit we will need three layers: ", None))
        self.label_9.setText(_translate("EQWizard", "countries.shp, plate_boundaries.shp and", None))
        self.label_10.setText(_translate("EQWizard", "earthquakes_2011.shp. Use the Browse", None))
        self.label_11.setText(_translate("EQWizard", "buttons below to select these layers from", None))
        self.label_12.setText(_translate("EQWizard", "the Earthquakes data file.", None))
        self.platesBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.label_13.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_2.setText(_translate("EQWizard", "0", None))
        self.textBrowser_2.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We can use colour to distinguish between earthquakes of different magnitudes. Experiment with the colour and column options below. Make sure that you choose </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Graduated</span><span style=\" font-size:10pt;\"> and the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Magnitude</span><span style=\" font-size:10pt;\"> column before you click </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Next</span><span style=\" font-size:10pt;\"> as this will help with the next steps.</span></p></body></html>", None))
        self.label_14.setText(_translate("EQWizard", "Colour Schemes", None))
        self.groupBox_4.setTitle(_translate("EQWizard", "Style Earthquakes Layer", None))
        self.columnLabel.setText(_translate("EQWizard", "Column:", None))
        self.ChangeColourButton.setText(_translate("EQWizard", "Colour", None))
        self.StyleTypecomboBox.setItemText(0, _translate("EQWizard", "Single Colour", None))
        self.StyleTypecomboBox.setItemText(1, _translate("EQWizard", "Graduated", None))
        self.colourRampLabel.setText(_translate("EQWizard", "Colour Ramp:", None))
        self.textBrowser_3.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Although we have used colour to differentiate earthquakes of different magnitudes, there are so many that it is still quite difficult to pick out the largest ones. To make the difference between earthquake magnitudes more clear, we can use </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">proportional symbols</span><span style=\" font-size:10pt;\"> based on </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Magnitude</span><span style=\" font-size:10pt;\">.</span></p></body></html>", None))
        self.label_15.setText(_translate("EQWizard", "Proportional Symbols", None))
        self.groupBox.setTitle(_translate("EQWizard", "Proportional Symbols", None))
        self.scaleCheckBox.setText(_translate("EQWizard", "Use proportional symbols", None))
        self.scaleComboBox.setItemText(0, _translate("EQWizard", "Magnitude", None))
        self.scaleComboBox.setItemText(1, _translate("EQWizard", "latitude", None))
        self.scaleComboBox.setItemText(2, _translate("EQWizard", "longitude", None))
        self.label_16.setText(_translate("EQWizard", "column:", None))
        self.label_17.setText(_translate("EQWizard", "Scale based on ", None))
        self.groupBox_2.setTitle(_translate("EQWizard", "1.", None))
        self.fourSix.setText(_translate("EQWizard", "4.0 - 6.0", None))
        self.twoFour.setText(_translate("EQWizard", "2.0 - 4.0", None))
        self.sixEight.setText(_translate("EQWizard", "6.0 - 8.0", None))
        self.label_18.setText(_translate("EQWizard", "What magnitude range do the earthquakes", None))
        self.zeroTwo.setText(_translate("EQWizard", "0.0 - 2.0", None))
        self.label_23.setText(_translate("EQWizard", "in the UK fall into?", None))
        self.label_22.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_3.setText(_translate("EQWizard", "0", None))
        self.checkAnswersMag.setText(_translate("EQWizard", "Check my answer!", None))
        self.label_19.setText(_translate("EQWizard", "Buffering", None))
        self.textBrowser_4.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">GIS can also help us answer more difficult questions, such as </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">&quot;how many earthquakes are within 10</span><span style=\" font-size:10pt; font-weight:600; color:#00007f; vertical-align:super;\">o</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> of a plate boundary?&quot;</span><span style=\" font-size:10pt;\">. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The first step towards addressing this question is to find the area that is within 10</span><span style=\" font-size:10pt; vertical-align:super;\">o</span><span style=\" font-size:10pt;\"> of the plate boundaries. To do this, we need to create a</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> buffer</span><span style=\" font-size:10pt;\">. Input </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">plate_boudaries</span><span style=\" font-size:10pt;\"> as the input file and </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">10 </span><span style=\" font-size:10pt;\">for the buffer distance below, then select a suitable place to save the output file and click </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Create Buffer!</span></p></body></html>", None))
        self.label_24.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_4.setText(_translate("EQWizard", "0", None))
        self.groupBox_3.setTitle(_translate("EQWizard", "Buffer", None))
        self.label_25.setText(_translate("EQWizard", "Output shapefile:", None))
        self.label_20.setText(_translate("EQWizard", "Input Layer:", None))
        self.bufferBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.label_21.setText(_translate("EQWizard", "Buffer distance:", None))
        self.inputComboBox.setItemText(0, _translate("EQWizard", "earthquakes", None))
        self.inputComboBox.setItemText(1, _translate("EQWizard", "plate_boundaries", None))
        self.inputComboBox.setItemText(2, _translate("EQWizard", "countries", None))
        self.bufferButton.setText(_translate("EQWizard", "Create Buffer!", None))
        self.textBrowser_5.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The new buffer layer clearly shows the area within 10</span><span style=\" font-size:10pt; vertical-align:super;\">o</span><span style=\" font-size:10pt;\"> of the plate boundaries. It currently obscures our view of the earthquakes, however. Restyle it so that you can see the earthquakes through the buffer.</span></p></body></html>", None))
        self.label_26.setText(_translate("EQWizard", "Re-styling Buffers", None))
        self.label_27.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_5.setText(_translate("EQWizard", "0", None))
        self.groupBox_5.setTitle(_translate("EQWizard", "Style Buffer Layer", None))
        self.transparencyButton.setText(_translate("EQWizard", "Apply Transparency", None))
        self.bufferColourButton.setText(_translate("EQWizard", "Colour", None))
        self.label_29.setText(_translate("EQWizard", "Set buffer colour:", None))
        self.label_30.setText(_translate("EQWizard", "Transparency:", None))
        self.groupBox_6.setTitle(_translate("EQWizard", "2.", None))
        self.arcticCircle.setText(_translate("EQWizard", "They only occur above the arctic circle", None))
        self.plates.setText(_translate("EQWizard", "They are mostly on or near plate boundaries", None))
        self.equator.setText(_translate("EQWizard", "They only occur on the equator", None))
        self.label_28.setText(_translate("EQWizard", "Which statement most accurately describes ", None))
        self.even.setText(_translate("EQWizard", "They are evenly distributed across the globe", None))
        self.label_31.setText(_translate("EQWizard", "the distribution pattern of the earthquakes?", None))
        self.checkAnswersDist.setText(_translate("EQWizard", "Check my answer!", None))
        self.textBrowser_6.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The next step towards answering the question </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">&quot;how many earthquakes are within 10</span><span style=\" font-size:10pt; font-weight:600; color:#00007f; vertical-align:super;\">o</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> of a plate boundary?&quot; </span><span style=\" font-size:10pt; color:#000000;\">is to count up the number of earthquakes that are within the buffer. We could count them by hand, but it is much quicker and easier to use </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Spatial Query</span><span style=\" font-size:10pt; color:#000000;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">We want to select the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">earthquakes</span><span style=\" font-size:10pt; color:#000000;\"> that are</span><span style=\" font-size:10pt; font-weight:600; color:#000000;\"> </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">within</span><span style=\" font-size:10pt; color:#000000;\"> the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">buffer layer</span><span style=\" font-size:10pt; color:#000000;\">. See if you can use the options below to make a new layer of plate boundary earthquakes.</span></p></body></html>", None))
        self.label_32.setText(_translate("EQWizard", "Spatial Query", None))
        self.newLayergroupBox.setTitle(_translate("EQWizard", "New Layer", None))
        self.newLayercheckBox.setText(_translate("EQWizard", "Make a new layer from the selection", None))
        self.queryBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.label_33.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_6.setText(_translate("EQWizard", "0", None))
        self.clearSelection.setText(_translate("EQWizard", "Clear Selection", None))
        self.runQuery.setText(_translate("EQWizard", "Run Query!", None))
        self.label_34.setText(_translate("EQWizard", "Select from input layer:", None))
        self.label_35.setText(_translate("EQWizard", "With reference layer:", None))
        self.label_36.setText(_translate("EQWizard", "Where the input layer is :", None))
        self.label_37.setText(_translate("EQWizard", "the reference layer", None))
        self.Score_label_7.setText(_translate("EQWizard", "0", None))
        self.label_38.setText(_translate("EQWizard", "Your Score:", None))
        self.textBrowser_7.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We can now answer the question </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">&quot;how many earthquakes are within 10</span><span style=\" font-size:10pt; font-weight:600; color:#00007f; vertical-align:super;\">o</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> of a plate boundary?&quot;</span><span style=\" font-size:10pt;\"> by looking at the attribute table of the new layer which contains information relating to each earthquake within the buffer. Use the table below to answer the question.</span></p></body></html>", None))
        self.label_39.setText(_translate("EQWizard", "Attribute Tables", None))
        self.checkAnswersNum.setText(_translate("EQWizard", "Check my answer!", None))
        self.groupBox_7.setTitle(_translate("EQWizard", "3.", None))
        self.label_41.setText(_translate("EQWizard", "How many earthquakes are within 10 ", None))
        self.label_42.setText(_translate("EQWizard", "degrees of a plate boundary?", None))
        self.label_40.setText(_translate("EQWizard", "Layer:", None))
        self.groupBox_8.setTitle(_translate("EQWizard", "4.", None))
        self.settlement.setText(_translate("EQWizard", "The closest settlement to the focus", None))
        self.focus.setText(_translate("EQWizard", "The point inside the crust where the earthquake", None))
        self.epicentre.setText(_translate("EQWizard", "The point on the Earth\'s surface above the", None))
        self.label_43.setText(_translate("EQWizard", "What is an earthquake epicentre?", None))
        self.eR.setText(_translate("EQWizard", "An emergency response centre", None))
        self.label_49.setText(_translate("EQWizard", "place in the crust where pressure is released", None))
        self.label_50.setText(_translate("EQWizard", "originates", None))
        self.groupBox_9.setTitle(_translate("EQWizard", "5.", None))
        self.cities.setText(_translate("EQWizard", "Because there are more cities in these areas", None))
        self.plateMovement.setText(_translate("EQWizard", "The movement of plates build up pressure", None))
        self.climate.setText(_translate("EQWizard", "Because the climate in these areas induce", None))
        self.label_44.setText(_translate("EQWizard", "Why do the majority of earthquakes occur", None))
        self.mining.setText(_translate("EQWizard", "Because more mining work takes place in these", None))
        self.label_45.setText(_translate("EQWizard", "on or near a plate boundary?", None))
        self.label_51.setText(_translate("EQWizard", "which is released as an earthquake", None))
        self.label_52.setText(_translate("EQWizard", "regions", None))
        self.label_53.setText(_translate("EQWizard", "earthquakes", None))
        self.label_46.setText(_translate("EQWizard", "Question Time", None))
        self.label_47.setText(_translate("EQWizard", "Use your knowledge of earthquakes to ", None))
        self.Score_label_8.setText(_translate("EQWizard", "0", None))
        self.label_48.setText(_translate("EQWizard", "Your Score:", None))
        self.checkAnswersEQ.setText(_translate("EQWizard", "Check my answers!", None))
        self.label_54.setText(_translate("EQWizard", "answer the following questions:", None))
        self.groupBox_10.setTitle(_translate("EQWizard", "Layers", None))
        self.lyrCheckBox.setText(_translate("EQWizard", "CheckBox", None))
        self.lyrCheckBox_2.setText(_translate("EQWizard", "CheckBox", None))
        self.lyrCheckBox_3.setText(_translate("EQWizard", "CheckBox", None))
        self.lyrCheckBox_4.setText(_translate("EQWizard", "CheckBox", None))
        self.lyrCheckBox_5.setText(_translate("EQWizard", "CheckBox", None))
        self.Score_label_9.setText(_translate("EQWizard", "0", None))
        self.label_59.setText(_translate("EQWizard", "Your Score:", None))
        self.textBrowser_8.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Use the check boxes below to explore the layers you have added. Ensure that you leave only the checkboxes for</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> countries</span><span style=\" font-size:10pt;\"> and your new earthquakes on plate boundaries layer checked before you click next as this will help you with the next step.</span></p></body></html>", None))
        self.label_60.setText(_translate("EQWizard", "Exploring Layers", None))
        self.groupBox_11.setTitle(_translate("EQWizard", "6.", None))
        self.fire.setText(_translate("EQWizard", "Fires", None))
        self.shake.setText(_translate("EQWizard", "Buildings shake", None))
        self.income.setText(_translate("EQWizard", "Loss of income", None))
        self.label_61.setText(_translate("EQWizard", "Whic of the following  is a primary effect", None))
        self.disease.setText(_translate("EQWizard", "Spread of disease", None))
        self.label_62.setText(_translate("EQWizard", "of an earthquake?", None))
        self.checkAnswersEffects.setText(_translate("EQWizard", "Check my answers!", None))
        self.Score_label_10.setText(_translate("EQWizard", "0", None))
        self.label_63.setText(_translate("EQWizard", "Your Score:", None))
        self.label_64.setText(_translate("EQWizard", "Further Enquiry", None))
        self.textBrowser.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We can use the new layer that we have created to answer even more complicated questions such as </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">&quot;how many earthquakes took place in 2011 that were within 10</span><span style=\" font-size:10pt; font-weight:600; color:#00007f; vertical-align:super;\">o</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> of a plate boundary and were also in the tropics?&quot; </span><span style=\" font-size:10pt; color:#000000;\">The tropics can be defined as the area 23.5</span><span style=\" font-size:10pt; color:#000000; vertical-align:super;\">o</span><span style=\" font-size:10pt; color:#000000;\"> north and south of the equator. We can find this area with a buffer around the equator, but first we must add it to the map canvas.</span></p></body></html>", None))
        self.groupBox_12.setTitle(_translate("EQWizard", "Buffer", None))
        self.label_56.setText(_translate("EQWizard", "Output shapefile:", None))
        self.label_57.setText(_translate("EQWizard", "Input Layer:", None))
        self.bufferBrowseButton_2.setText(_translate("EQWizard", "Browse", None))
        self.label_58.setText(_translate("EQWizard", "Buffer distance:", None))
        self.inputComboBox_3.setItemText(0, _translate("EQWizard", "earthquakes", None))
        self.inputComboBox_3.setItemText(1, _translate("EQWizard", "plate_boundaries", None))
        self.inputComboBox_3.setItemText(2, _translate("EQWizard", "countries", None))
        self.bufferButton_2.setText(_translate("EQWizard", "Create Buffer!", None))
        self.label_65.setText(_translate("EQWizard", "Create a buffer of 23.5 degrees around the equator.", None))
        self.groupBox_13.setTitle(_translate("EQWizard", "Add the equator", None))
        self.equatorBrowseButton.setText(_translate("EQWizard", "Browse", None))
        self.AddLayerButton_2.setText(_translate("EQWizard", "Add Layer!", None))
        self.label_55.setText(_translate("EQWizard", "Where the input layer is :", None))
        self.label_66.setText(_translate("EQWizard", "the reference layer", None))
        self.runQuery_2.setText(_translate("EQWizard", "Run Query!", None))
        self.newLayergroupBox_2.setTitle(_translate("EQWizard", "New Layer", None))
        self.newLayercheckBox_2.setText(_translate("EQWizard", "Make a new layer from the selection", None))
        self.queryBrowseButton_2.setText(_translate("EQWizard", "Browse", None))
        self.label_67.setText(_translate("EQWizard", "With reference layer:", None))
        self.label_68.setText(_translate("EQWizard", "Select from input layer:", None))
        self.clearSelection_2.setText(_translate("EQWizard", "Clear Selection", None))
        self.label_69.setText(_translate("EQWizard", "Your Score:", None))
        self.Score_label_11.setText(_translate("EQWizard", "0", None))
        self.label_70.setText(_translate("EQWizard", "Further Enquiry", None))
        self.textBrowser_9.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We can now use the spatial query functionality provided blow to make a layer of just those earthquakes that are within 10</span><span style=\" font-size:10pt; vertical-align:super;\">o</span><span style=\" font-size:10pt;\"> of a plate boundary and is within the tropics.</span></p></body></html>", None))
        self.label_71.setText(_translate("EQWizard", "Layer:", None))
        self.checkAnswersNum_2.setText(_translate("EQWizard", "Check my answer!", None))
        self.label_72.setText(_translate("EQWizard", "Attribute Tables", None))
        self.groupBox_14.setTitle(_translate("EQWizard", "7.", None))
        self.label_73.setText(_translate("EQWizard", "How many earthquakes are within 10 ", None))
        self.label_74.setText(_translate("EQWizard", "degrees of a plate boundary and also", None))
        self.label_76.setText(_translate("EQWizard", "occurred in the tropics?", None))
        self.textBrowser_10.setHtml(_translate("EQWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">We can now answer the question </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">&quot;how many earthquakes took place in 2011 that were within 10</span><span style=\" font-size:10pt; font-weight:600; color:#00007f; vertical-align:super;\">o</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> of a plate boundary and were also in the tropics?&quot;</span><span style=\" font-size:10pt; color:#000000;\"> using the attribute table below.</span></p></body></html>", None))
        self.Score_label_12.setText(_translate("EQWizard", "0", None))
        self.label_75.setText(_translate("EQWizard", "Your Score:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EQWizard = QtGui.QWizard()
    ui = Ui_EQWizard()
    ui.setupUi(EQWizard)
    EQWizard.show()
    sys.exit(app.exec_())

