# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charlottegraves\.qgis2\python\plugins\QGISforSchools\Pop_dev_wizard.ui'
#
# Created: Mon Jun 16 14:14:27 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PopDevWizard(object):
    def setupUi(self, PopDevWizard):
        PopDevWizard.setObjectName(_fromUtf8("PopDevWizard"))
        PopDevWizard.resize(293, 591)
        PopDevWizard.setSizeGripEnabled(True)
        PopDevWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        PopDevWizard.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.IntrotextBrowser = QtGui.QTextBrowser(self.wizardPage1)
        self.IntrotextBrowser.setGeometry(QtCore.QRect(20, 30, 256, 481))
        self.IntrotextBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.IntrotextBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.IntrotextBrowser.setObjectName(_fromUtf8("IntrotextBrowser"))
        PopDevWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.CountrieslineEdit = QtGui.QLineEdit(self.wizardPage2)
        self.CountrieslineEdit.setGeometry(QtCore.QRect(20, 300, 171, 20))
        self.CountrieslineEdit.setObjectName(_fromUtf8("CountrieslineEdit"))
        self.CountriesBrowseButton = QtGui.QPushButton(self.wizardPage2)
        self.CountriesBrowseButton.setGeometry(QtCore.QRect(200, 300, 75, 23))
        self.CountriesBrowseButton.setObjectName(_fromUtf8("CountriesBrowseButton"))
        self.AddCountriesLayerButton = QtGui.QPushButton(self.wizardPage2)
        self.AddCountriesLayerButton.setGeometry(QtCore.QRect(20, 340, 251, 21))
        self.AddCountriesLayerButton.setObjectName(_fromUtf8("AddCountriesLayerButton"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.wizardPage2)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 390, 251, 71))
        self.textBrowser_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_3.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.label = QtGui.QLabel(self.wizardPage2)
        self.label.setGeometry(QtCore.QRect(150, 498, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.Score_label = QtGui.QLabel(self.wizardPage2)
        self.Score_label.setGeometry(QtCore.QRect(230, 500, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label.setFont(font)
        self.Score_label.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label.setObjectName(_fromUtf8("Score_label"))
        self.textBrowser = QtGui.QTextBrowser(self.wizardPage2)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 256, 261))
        self.textBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        PopDevWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.categoryTableView = QtGui.QTableView(self.wizardPage3)
        self.categoryTableView.setGeometry(QtCore.QRect(20, 271, 256, 191))
        self.categoryTableView.setShowGrid(False)
        self.categoryTableView.setObjectName(_fromUtf8("categoryTableView"))
        self.Score_label_2 = QtGui.QLabel(self.wizardPage3)
        self.Score_label_2.setGeometry(QtCore.QRect(230, 502, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_2.setFont(font)
        self.Score_label_2.setFrameShape(QtGui.QFrame.Box)
        self.Score_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_2.setObjectName(_fromUtf8("Score_label_2"))
        self.label_2 = QtGui.QLabel(self.wizardPage3)
        self.label_2.setGeometry(QtCore.QRect(150, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.wizardPage3)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 271, 161))
        self.textBrowser_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.StyleTypecomboBox = QtGui.QComboBox(self.wizardPage3)
        self.StyleTypecomboBox.setGeometry(QtCore.QRect(30, 180, 111, 21))
        self.StyleTypecomboBox.setObjectName(_fromUtf8("StyleTypecomboBox"))
        self.StyleTypecomboBox.addItem(_fromUtf8(""))
        self.StyleTypecomboBox.addItem(_fromUtf8(""))
        self.ColourRampcomboBox = QtGui.QComboBox(self.wizardPage3)
        self.ColourRampcomboBox.setEnabled(False)
        self.ColourRampcomboBox.setGeometry(QtCore.QRect(150, 240, 111, 21))
        self.ColourRampcomboBox.setObjectName(_fromUtf8("ColourRampcomboBox"))
        self.ChangeColourButton = QtGui.QPushButton(self.wizardPage3)
        self.ChangeColourButton.setGeometry(QtCore.QRect(150, 180, 111, 21))
        self.ChangeColourButton.setObjectName(_fromUtf8("ChangeColourButton"))
        self.ColumncomboBox = QtGui.QComboBox(self.wizardPage3)
        self.ColumncomboBox.setEnabled(False)
        self.ColumncomboBox.setGeometry(QtCore.QRect(110, 210, 151, 20))
        self.ColumncomboBox.setObjectName(_fromUtf8("ColumncomboBox"))
        self.columnLabel = QtGui.QLabel(self.wizardPage3)
        self.columnLabel.setEnabled(False)
        self.columnLabel.setGeometry(QtCore.QRect(30, 210, 41, 16))
        self.columnLabel.setObjectName(_fromUtf8("columnLabel"))
        self.colourRampLabel = QtGui.QLabel(self.wizardPage3)
        self.colourRampLabel.setEnabled(False)
        self.colourRampLabel.setGeometry(QtCore.QRect(30, 240, 81, 16))
        self.colourRampLabel.setObjectName(_fromUtf8("colourRampLabel"))
        PopDevWizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.Score_label_3 = QtGui.QLabel(self.wizardPage4)
        self.Score_label_3.setGeometry(QtCore.QRect(230, 502, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_3.setFont(font)
        self.Score_label_3.setFrameShape(QtGui.QFrame.Box)
        self.Score_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_3.setObjectName(_fromUtf8("Score_label_3"))
        self.label_3 = QtGui.QLabel(self.wizardPage4)
        self.label_3.setGeometry(QtCore.QRect(150, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.checkAnswersPop = QtGui.QPushButton(self.wizardPage4)
        self.checkAnswersPop.setGeometry(QtCore.QRect(20, 450, 251, 21))
        self.checkAnswersPop.setObjectName(_fromUtf8("checkAnswersPop"))
        self.label_5 = QtGui.QLabel(self.wizardPage4)
        self.label_5.setGeometry(QtCore.QRect(70, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.wizardPage4)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.wizardPage4)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 271, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.smallPop = QtGui.QRadioButton(self.groupBox)
        self.smallPop.setGeometry(QtCore.QRect(50, 90, 161, 21))
        self.smallPop.setObjectName(_fromUtf8("smallPop"))
        self.mediumPop = QtGui.QRadioButton(self.groupBox)
        self.mediumPop.setGeometry(QtCore.QRect(50, 70, 161, 21))
        self.mediumPop.setObjectName(_fromUtf8("mediumPop"))
        self.largePop = QtGui.QRadioButton(self.groupBox)
        self.largePop.setGeometry(QtCore.QRect(50, 110, 161, 21))
        self.largePop.setObjectName(_fromUtf8("largePop"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.vSmallPop = QtGui.QRadioButton(self.groupBox)
        self.vSmallPop.setGeometry(QtCore.QRect(50, 50, 161, 21))
        self.vSmallPop.setObjectName(_fromUtf8("vSmallPop"))
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 270, 271, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.usaPop = QtGui.QRadioButton(self.groupBox_2)
        self.usaPop.setGeometry(QtCore.QRect(60, 130, 161, 21))
        self.usaPop.setObjectName(_fromUtf8("usaPop"))
        self.norwayPop = QtGui.QRadioButton(self.groupBox_2)
        self.norwayPop.setGeometry(QtCore.QRect(60, 70, 161, 21))
        self.norwayPop.setObjectName(_fromUtf8("norwayPop"))
        self.francePop = QtGui.QRadioButton(self.groupBox_2)
        self.francePop.setGeometry(QtCore.QRect(60, 110, 161, 21))
        self.francePop.setObjectName(_fromUtf8("francePop"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.brazilPop = QtGui.QRadioButton(self.groupBox_2)
        self.brazilPop.setGeometry(QtCore.QRect(60, 90, 161, 21))
        self.brazilPop.setObjectName(_fromUtf8("brazilPop"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        PopDevWizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName(_fromUtf8("wizardPage5"))
        self.label_10 = QtGui.QLabel(self.wizardPage5)
        self.label_10.setGeometry(QtCore.QRect(150, 498, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ColourRampcomboBox_2 = QtGui.QComboBox(self.wizardPage5)
        self.ColourRampcomboBox_2.setEnabled(True)
        self.ColourRampcomboBox_2.setGeometry(QtCore.QRect(150, 240, 111, 21))
        self.ColourRampcomboBox_2.setObjectName(_fromUtf8("ColourRampcomboBox_2"))
        self.ChangeColourButton_2 = QtGui.QPushButton(self.wizardPage5)
        self.ChangeColourButton_2.setEnabled(False)
        self.ChangeColourButton_2.setGeometry(QtCore.QRect(150, 180, 111, 21))
        self.ChangeColourButton_2.setObjectName(_fromUtf8("ChangeColourButton_2"))
        self.colourRampLabel_2 = QtGui.QLabel(self.wizardPage5)
        self.colourRampLabel_2.setEnabled(True)
        self.colourRampLabel_2.setGeometry(QtCore.QRect(30, 240, 81, 16))
        self.colourRampLabel_2.setObjectName(_fromUtf8("colourRampLabel_2"))
        self.StyleTypecomboBox_2 = QtGui.QComboBox(self.wizardPage5)
        self.StyleTypecomboBox_2.setGeometry(QtCore.QRect(30, 180, 111, 21))
        self.StyleTypecomboBox_2.setObjectName(_fromUtf8("StyleTypecomboBox_2"))
        self.StyleTypecomboBox_2.addItem(_fromUtf8(""))
        self.StyleTypecomboBox_2.addItem(_fromUtf8(""))
        self.categoryTableView_2 = QtGui.QTableView(self.wizardPage5)
        self.categoryTableView_2.setGeometry(QtCore.QRect(20, 271, 256, 191))
        self.categoryTableView_2.setShowGrid(False)
        self.categoryTableView_2.setObjectName(_fromUtf8("categoryTableView_2"))
        self.ColumncomboBox_2 = QtGui.QComboBox(self.wizardPage5)
        self.ColumncomboBox_2.setEnabled(True)
        self.ColumncomboBox_2.setGeometry(QtCore.QRect(110, 210, 151, 20))
        self.ColumncomboBox_2.setObjectName(_fromUtf8("ColumncomboBox_2"))
        self.ColumncomboBox_2.addItem(_fromUtf8(""))
        self.ColumncomboBox_2.addItem(_fromUtf8(""))
        self.ColumncomboBox_2.addItem(_fromUtf8(""))
        self.Score_label_4 = QtGui.QLabel(self.wizardPage5)
        self.Score_label_4.setGeometry(QtCore.QRect(230, 500, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_4.setFont(font)
        self.Score_label_4.setFrameShape(QtGui.QFrame.Box)
        self.Score_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_4.setObjectName(_fromUtf8("Score_label_4"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.wizardPage5)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 70, 261, 91))
        self.textBrowser_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_4.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.columnLabel_2 = QtGui.QLabel(self.wizardPage5)
        self.columnLabel_2.setEnabled(True)
        self.columnLabel_2.setGeometry(QtCore.QRect(30, 210, 41, 16))
        self.columnLabel_2.setObjectName(_fromUtf8("columnLabel_2"))
        self.label_11 = QtGui.QLabel(self.wizardPage5)
        self.label_11.setGeometry(QtCore.QRect(60, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        PopDevWizard.addPage(self.wizardPage5)
        self.wizardPage6 = QtGui.QWizardPage()
        self.wizardPage6.setObjectName(_fromUtf8("wizardPage6"))
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage6)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 108, 271, 151))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.sAmerica = QtGui.QRadioButton(self.groupBox_3)
        self.sAmerica.setGeometry(QtCore.QRect(60, 100, 161, 21))
        self.sAmerica.setObjectName(_fromUtf8("sAmerica"))
        self.asia = QtGui.QRadioButton(self.groupBox_3)
        self.asia.setGeometry(QtCore.QRect(60, 80, 161, 21))
        self.asia.setObjectName(_fromUtf8("asia"))
        self.europe = QtGui.QRadioButton(self.groupBox_3)
        self.europe.setGeometry(QtCore.QRect(60, 120, 161, 21))
        self.europe.setObjectName(_fromUtf8("europe"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.africa = QtGui.QRadioButton(self.groupBox_3)
        self.africa.setGeometry(QtCore.QRect(60, 60, 161, 21))
        self.africa.setObjectName(_fromUtf8("africa"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.groupBox_4 = QtGui.QGroupBox(self.wizardPage6)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 268, 271, 161))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.tla = QtGui.QRadioButton(self.groupBox_4)
        self.tla.setGeometry(QtCore.QRect(60, 120, 161, 21))
        self.tla.setObjectName(_fromUtf8("tla"))
        self.imj = QtGui.QRadioButton(self.groupBox_4)
        self.imj.setGeometry(QtCore.QRect(60, 60, 161, 21))
        self.imj.setObjectName(_fromUtf8("imj"))
        self.spm = QtGui.QRadioButton(self.groupBox_4)
        self.spm.setGeometry(QtCore.QRect(60, 100, 161, 21))
        self.spm.setObjectName(_fromUtf8("spm"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.ufi = QtGui.QRadioButton(self.groupBox_4)
        self.ufi.setGeometry(QtCore.QRect(60, 80, 161, 21))
        self.ufi.setObjectName(_fromUtf8("ufi"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.wizardPage6)
        self.label_15.setGeometry(QtCore.QRect(20, 68, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.wizardPage6)
        self.label_16.setGeometry(QtCore.QRect(20, 48, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.wizardPage6)
        self.label_17.setGeometry(QtCore.QRect(70, 8, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.checkAnswersDev = QtGui.QPushButton(self.wizardPage6)
        self.checkAnswersDev.setGeometry(QtCore.QRect(20, 448, 251, 21))
        self.checkAnswersDev.setObjectName(_fromUtf8("checkAnswersDev"))
        self.label_18 = QtGui.QLabel(self.wizardPage6)
        self.label_18.setGeometry(QtCore.QRect(150, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.Score_label_5 = QtGui.QLabel(self.wizardPage6)
        self.Score_label_5.setGeometry(QtCore.QRect(230, 500, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_5.setFont(font)
        self.Score_label_5.setFrameShape(QtGui.QFrame.Box)
        self.Score_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_5.setObjectName(_fromUtf8("Score_label_5"))
        PopDevWizard.addPage(self.wizardPage6)
        self.wizardPage7 = QtGui.QWizardPage()
        self.wizardPage7.setObjectName(_fromUtf8("wizardPage7"))
        self.IntrotextBrowser_2 = QtGui.QTextBrowser(self.wizardPage7)
        self.IntrotextBrowser_2.setGeometry(QtCore.QRect(20, 40, 256, 241))
        self.IntrotextBrowser_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.IntrotextBrowser_2.setFrameShadow(QtGui.QFrame.Plain)
        self.IntrotextBrowser_2.setObjectName(_fromUtf8("IntrotextBrowser_2"))
        self.AddObesityLayerButton = QtGui.QPushButton(self.wizardPage7)
        self.AddObesityLayerButton.setGeometry(QtCore.QRect(20, 350, 251, 21))
        self.AddObesityLayerButton.setObjectName(_fromUtf8("AddObesityLayerButton"))
        self.Score_label_6 = QtGui.QLabel(self.wizardPage7)
        self.Score_label_6.setGeometry(QtCore.QRect(230, 502, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_6.setFont(font)
        self.Score_label_6.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_6.setObjectName(_fromUtf8("Score_label_6"))
        self.obesitylineEdit = QtGui.QLineEdit(self.wizardPage7)
        self.obesitylineEdit.setGeometry(QtCore.QRect(20, 310, 171, 20))
        self.obesitylineEdit.setObjectName(_fromUtf8("obesitylineEdit"))
        self.textBrowser_5 = QtGui.QTextBrowser(self.wizardPage7)
        self.textBrowser_5.setGeometry(QtCore.QRect(20, 400, 251, 41))
        self.textBrowser_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_5.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.label_20 = QtGui.QLabel(self.wizardPage7)
        self.label_20.setGeometry(QtCore.QRect(150, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.obesityBrowseButton = QtGui.QPushButton(self.wizardPage7)
        self.obesityBrowseButton.setGeometry(QtCore.QRect(200, 310, 75, 23))
        self.obesityBrowseButton.setObjectName(_fromUtf8("obesityBrowseButton"))
        self.label_21 = QtGui.QLabel(self.wizardPage7)
        self.label_21.setGeometry(QtCore.QRect(30, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        PopDevWizard.addPage(self.wizardPage7)
        self.wizardPage8 = QtGui.QWizardPage()
        self.wizardPage8.setObjectName(_fromUtf8("wizardPage8"))
        self.groupBox_5 = QtGui.QGroupBox(self.wizardPage8)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 130, 251, 61))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.ColumncomboBox_3 = QtGui.QComboBox(self.groupBox_5)
        self.ColumncomboBox_3.setEnabled(True)
        self.ColumncomboBox_3.setGeometry(QtCore.QRect(90, 30, 151, 20))
        self.ColumncomboBox_3.setObjectName(_fromUtf8("ColumncomboBox_3"))
        self.columnLabel_3 = QtGui.QLabel(self.groupBox_5)
        self.columnLabel_3.setEnabled(True)
        self.columnLabel_3.setGeometry(QtCore.QRect(10, 30, 41, 16))
        self.columnLabel_3.setObjectName(_fromUtf8("columnLabel_3"))
        self.obesityTableView = QtGui.QTableView(self.wizardPage8)
        self.obesityTableView.setGeometry(QtCore.QRect(20, 300, 256, 171))
        self.obesityTableView.setObjectName(_fromUtf8("obesityTableView"))
        self.label_22 = QtGui.QLabel(self.wizardPage8)
        self.label_22.setGeometry(QtCore.QRect(150, 498, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.Score_label_7 = QtGui.QLabel(self.wizardPage8)
        self.Score_label_7.setGeometry(QtCore.QRect(230, 500, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_7.setFont(font)
        self.Score_label_7.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_7.setObjectName(_fromUtf8("Score_label_7"))
        self.groupBox_6 = QtGui.QGroupBox(self.wizardPage8)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 200, 251, 61))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.obesityColumncomboBox = QtGui.QComboBox(self.groupBox_6)
        self.obesityColumncomboBox.setEnabled(True)
        self.obesityColumncomboBox.setGeometry(QtCore.QRect(90, 30, 151, 20))
        self.obesityColumncomboBox.setObjectName(_fromUtf8("obesityColumncomboBox"))
        self.columnLabel_4 = QtGui.QLabel(self.groupBox_6)
        self.columnLabel_4.setEnabled(True)
        self.columnLabel_4.setGeometry(QtCore.QRect(10, 30, 41, 20))
        self.columnLabel_4.setObjectName(_fromUtf8("columnLabel_4"))
        self.colourRampLabel_3 = QtGui.QLabel(self.wizardPage8)
        self.colourRampLabel_3.setEnabled(True)
        self.colourRampLabel_3.setGeometry(QtCore.QRect(30, 270, 81, 16))
        self.colourRampLabel_3.setObjectName(_fromUtf8("colourRampLabel_3"))
        self.ColourRampcomboBox_3 = QtGui.QComboBox(self.wizardPage8)
        self.ColourRampcomboBox_3.setEnabled(True)
        self.ColourRampcomboBox_3.setGeometry(QtCore.QRect(150, 270, 111, 21))
        self.ColourRampcomboBox_3.setObjectName(_fromUtf8("ColourRampcomboBox_3"))
        self.label_23 = QtGui.QLabel(self.wizardPage8)
        self.label_23.setGeometry(QtCore.QRect(30, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.textBrowser_6 = QtGui.QTextBrowser(self.wizardPage8)
        self.textBrowser_6.setGeometry(QtCore.QRect(10, 30, 281, 101))
        self.textBrowser_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_6.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        PopDevWizard.addPage(self.wizardPage8)
        self.wizardPage9 = QtGui.QWizardPage()
        self.wizardPage9.setObjectName(_fromUtf8("wizardPage9"))
        self.countriesCheckBox = QtGui.QCheckBox(self.wizardPage9)
        self.countriesCheckBox.setGeometry(QtCore.QRect(140, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countriesCheckBox.setFont(font)
        self.countriesCheckBox.setChecked(True)
        self.countriesCheckBox.setObjectName(_fromUtf8("countriesCheckBox"))
        self.label_24 = QtGui.QLabel(self.wizardPage9)
        self.label_24.setGeometry(QtCore.QRect(30, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.wizardPage9)
        self.label_25.setGeometry(QtCore.QRect(20, 40, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.wizardPage9)
        self.label_26.setGeometry(QtCore.QRect(20, 60, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.wizardPage9)
        self.label_27.setGeometry(QtCore.QRect(20, 80, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.groupBox_7 = QtGui.QGroupBox(self.wizardPage9)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 130, 271, 151))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.hihi = QtGui.QRadioButton(self.groupBox_7)
        self.hihi.setGeometry(QtCore.QRect(60, 100, 201, 21))
        self.hihi.setObjectName(_fromUtf8("hihi"))
        self.vlovlo = QtGui.QRadioButton(self.groupBox_7)
        self.vlovlo.setGeometry(QtCore.QRect(60, 80, 181, 21))
        self.vlovlo.setObjectName(_fromUtf8("vlovlo"))
        self.hivhi = QtGui.QRadioButton(self.groupBox_7)
        self.hivhi.setGeometry(QtCore.QRect(60, 120, 201, 21))
        self.hivhi.setObjectName(_fromUtf8("hivhi"))
        self.label_28 = QtGui.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.hilo = QtGui.QRadioButton(self.groupBox_7)
        self.hilo.setGeometry(QtCore.QRect(60, 60, 181, 21))
        self.hilo.setObjectName(_fromUtf8("hilo"))
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        self.label_29.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.obesityCheckBox = QtGui.QCheckBox(self.wizardPage9)
        self.obesityCheckBox.setGeometry(QtCore.QRect(60, 110, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.obesityCheckBox.setFont(font)
        self.obesityCheckBox.setChecked(True)
        self.obesityCheckBox.setObjectName(_fromUtf8("obesityCheckBox"))
        self.groupBox_8 = QtGui.QGroupBox(self.wizardPage9)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 280, 271, 161))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.vLoOb = QtGui.QRadioButton(self.groupBox_8)
        self.vLoOb.setGeometry(QtCore.QRect(60, 120, 171, 21))
        self.vLoOb.setObjectName(_fromUtf8("vLoOb"))
        self.hiOb = QtGui.QRadioButton(self.groupBox_8)
        self.hiOb.setGeometry(QtCore.QRect(60, 60, 181, 21))
        self.hiOb.setObjectName(_fromUtf8("hiOb"))
        self.hiOb_2 = QtGui.QRadioButton(self.groupBox_8)
        self.hiOb_2.setGeometry(QtCore.QRect(60, 100, 201, 21))
        self.hiOb_2.setObjectName(_fromUtf8("hiOb_2"))
        self.label_30 = QtGui.QLabel(self.groupBox_8)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.midOb = QtGui.QRadioButton(self.groupBox_8)
        self.midOb.setGeometry(QtCore.QRect(60, 80, 161, 21))
        self.midOb.setObjectName(_fromUtf8("midOb"))
        self.label_31 = QtGui.QLabel(self.groupBox_8)
        self.label_31.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.Score_label_8 = QtGui.QLabel(self.wizardPage9)
        self.Score_label_8.setGeometry(QtCore.QRect(230, 502, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_8.setFont(font)
        self.Score_label_8.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_8.setObjectName(_fromUtf8("Score_label_8"))
        self.label_32 = QtGui.QLabel(self.wizardPage9)
        self.label_32.setGeometry(QtCore.QRect(150, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.checkAnswersObs = QtGui.QPushButton(self.wizardPage9)
        self.checkAnswersObs.setGeometry(QtCore.QRect(20, 450, 251, 21))
        self.checkAnswersObs.setObjectName(_fromUtf8("checkAnswersObs"))
        PopDevWizard.addPage(self.wizardPage9)
        self.wizardPage10 = QtGui.QWizardPage()
        self.wizardPage10.setObjectName(_fromUtf8("wizardPage10"))
        self.groupBox_9 = QtGui.QGroupBox(self.wizardPage10)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 190, 271, 261))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.a = QtGui.QRadioButton(self.groupBox_9)
        self.a.setGeometry(QtCore.QRect(20, 70, 241, 21))
        self.a.setObjectName(_fromUtf8("a"))
        self.c = QtGui.QRadioButton(self.groupBox_9)
        self.c.setGeometry(QtCore.QRect(20, 190, 221, 21))
        self.c.setObjectName(_fromUtf8("c"))
        self.b = QtGui.QRadioButton(self.groupBox_9)
        self.b.setGeometry(QtCore.QRect(20, 130, 231, 21))
        self.b.setObjectName(_fromUtf8("b"))
        self.label_48 = QtGui.QLabel(self.groupBox_9)
        self.label_48.setGeometry(QtCore.QRect(10, 20, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.groupBox_9)
        self.label_49.setGeometry(QtCore.QRect(10, 40, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_33 = QtGui.QLabel(self.groupBox_9)
        self.label_33.setGeometry(QtCore.QRect(40, 90, 221, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.groupBox_9)
        self.label_34.setGeometry(QtCore.QRect(40, 100, 221, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_37 = QtGui.QLabel(self.groupBox_9)
        self.label_37.setGeometry(QtCore.QRect(40, 150, 221, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_44 = QtGui.QLabel(self.groupBox_9)
        self.label_44.setGeometry(QtCore.QRect(40, 210, 221, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.groupBox_9)
        self.label_45.setGeometry(QtCore.QRect(40, 160, 221, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_50 = QtGui.QLabel(self.groupBox_9)
        self.label_50.setGeometry(QtCore.QRect(40, 220, 221, 16))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.Score_label_9 = QtGui.QLabel(self.wizardPage10)
        self.Score_label_9.setGeometry(QtCore.QRect(230, 502, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_9.setFont(font)
        self.Score_label_9.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_9.setObjectName(_fromUtf8("Score_label_9"))
        self.label_35 = QtGui.QLabel(self.wizardPage10)
        self.label_35.setGeometry(QtCore.QRect(150, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.wizardPage10)
        self.label_36.setGeometry(QtCore.QRect(40, 10, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_38 = QtGui.QLabel(self.wizardPage10)
        self.label_38.setGeometry(QtCore.QRect(20, 40, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.wizardPage10)
        self.label_39.setGeometry(QtCore.QRect(20, 60, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.wizardPage10)
        self.label_40.setGeometry(QtCore.QRect(20, 90, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.wizardPage10)
        self.label_41.setGeometry(QtCore.QRect(20, 110, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.wizardPage10)
        self.label_42.setGeometry(QtCore.QRect(20, 140, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.wizardPage10)
        self.label_43.setGeometry(QtCore.QRect(20, 160, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.checkAnswersPopDens = QtGui.QPushButton(self.wizardPage10)
        self.checkAnswersPopDens.setGeometry(QtCore.QRect(10, 460, 271, 21))
        self.checkAnswersPopDens.setObjectName(_fromUtf8("checkAnswersPopDens"))
        PopDevWizard.addPage(self.wizardPage10)
        self.wizardPage11 = QtGui.QWizardPage()
        self.wizardPage11.setObjectName(_fromUtf8("wizardPage11"))
        self.label_46 = QtGui.QLabel(self.wizardPage11)
        self.label_46.setGeometry(QtCore.QRect(30, 20, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.wizardPage11)
        self.label_47.setGeometry(QtCore.QRect(30, 50, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.starView = QtGui.QGraphicsView(self.wizardPage11)
        self.starView.setGeometry(QtCore.QRect(20, 260, 256, 192))
        self.starView.setObjectName(_fromUtf8("starView"))
        self.label_51 = QtGui.QLabel(self.wizardPage11)
        self.label_51.setGeometry(QtCore.QRect(50, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Levenim MT"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.Score_label_10 = QtGui.QLabel(self.wizardPage11)
        self.Score_label_10.setGeometry(QtCore.QRect(100, 160, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Score_label_10.setFont(font)
        self.Score_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_10.setObjectName(_fromUtf8("Score_label_10"))
        PopDevWizard.addPage(self.wizardPage11)

        self.retranslateUi(PopDevWizard)
        self.StyleTypecomboBox_2.setCurrentIndex(1)
        self.ColumncomboBox_2.setCurrentIndex(2)
        self.ColumncomboBox_3.setCurrentIndex(-1)
        self.obesityColumncomboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(PopDevWizard)

    def retranslateUi(self, PopDevWizard):
        PopDevWizard.setWindowTitle(_translate("PopDevWizard", "Population and Development", None))
        PopDevWizard.setToolTip(_translate("PopDevWizard", "Population and Development", None))
        PopDevWizard.setWhatsThis(_translate("PopDevWizard", "Population and Development", None))
        self.IntrotextBrowser.setWhatsThis(_translate("PopDevWizard", "Population & Development Intro", None))
        self.IntrotextBrowser.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Unit 1</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Global Population &amp; Development</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Maps can help you to visually compare countries\' characteristics whether they are physical ones like area or number of cities, or ones that you can\'t see, like population, national income or development.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"> A normal paper map would probably just display one or two of these aspects, but a system like QGIS can display many and can be manipulated very easily. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">In this unit you will explore the differences in the global distribution of population, income and development by changing the colour schemes of a map of the world.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You will be asked questions as you go. You will earn </span><span style=\" font-size:11pt; font-weight:600; color:#aa007f;\">5</span><span style=\" font-size:10pt;\"> points for getting the answer right first time, </span><span style=\" font-size:11pt; font-weight:600; color:#aa007f;\">3</span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\"> </span><span style=\" font-size:10pt;\">for getting it right second time and </span><span style=\" font-size:11pt; font-weight:600; color:#aa007f;\">1</span><span style=\" font-size:10pt;\"> for getting it right any time thereafter.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>", None))
        self.CountriesBrowseButton.setText(_translate("PopDevWizard", "Browse", None))
        self.AddCountriesLayerButton.setText(_translate("PopDevWizard", "Add Countries!", None))
        self.textBrowser_3.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">When the map of the world appears on the map canvas, click Next.</span></p></body></html>", None))
        self.label.setText(_translate("PopDevWizard", "Your Score:", None))
        self.Score_label.setText(_translate("PopDevWizard", "0", None))
        self.textBrowser.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Adding Layers</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">In every GIS project, you have to start by adding data to the map canvas. We are going to start by adding the countries of the world.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Click the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Browse</span><span style=\" font-size:10pt;\"> button below and navigate to the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Population &amp; Development</span><span style=\" font-size:10pt;\"> data folder and choose </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">countries.shp</span><span style=\" font-size:10pt;\">.</span></p></body></html>", None))
        self.Score_label_2.setText(_translate("PopDevWizard", "0", None))
        self.label_2.setText(_translate("PopDevWizard", "Your Score:", None))
        self.textBrowser_2.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Colour Schemes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Using colour we can compare national characteristics like population. Experiment with the colour and column options below. Make sure that you choose </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Categorized</span><span style=\" font-size:10pt;\"> and the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">pop_group</span><span style=\" font-size:10pt;\"> column before you click </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Next</span><span style=\" font-size:10pt;\"> as this will help you with the following questions.</span></p></body></html>", None))
        self.StyleTypecomboBox.setItemText(0, _translate("PopDevWizard", "Single Colour", None))
        self.StyleTypecomboBox.setItemText(1, _translate("PopDevWizard", "Categorized", None))
        self.ChangeColourButton.setText(_translate("PopDevWizard", "Colour", None))
        self.columnLabel.setText(_translate("PopDevWizard", "Column:", None))
        self.colourRampLabel.setText(_translate("PopDevWizard", "Colour Ramp:", None))
        self.Score_label_3.setText(_translate("PopDevWizard", "0", None))
        self.label_3.setText(_translate("PopDevWizard", "Your Score:", None))
        self.checkAnswersPop.setText(_translate("PopDevWizard", "Check my answers!", None))
        self.label_5.setText(_translate("PopDevWizard", "Question Time", None))
        self.label_6.setText(_translate("PopDevWizard", "Look at the map and answer the following", None))
        self.label_7.setText(_translate("PopDevWizard", "questions:", None))
        self.groupBox.setTitle(_translate("PopDevWizard", "1.", None))
        self.smallPop.setText(_translate("PopDevWizard", "Small Population", None))
        self.mediumPop.setText(_translate("PopDevWizard", "Medium Population", None))
        self.largePop.setText(_translate("PopDevWizard", "Large Population", None))
        self.label_4.setText(_translate("PopDevWizard", "What population group does the UK fall into?", None))
        self.vSmallPop.setText(_translate("PopDevWizard", "Very Small Population", None))
        self.groupBox_2.setTitle(_translate("PopDevWizard", "2.", None))
        self.usaPop.setText(_translate("PopDevWizard", "USA, India, China", None))
        self.norwayPop.setText(_translate("PopDevWizard", "Norway, Russia and Australia", None))
        self.francePop.setText(_translate("PopDevWizard", "France, Italy, Egypt", None))
        self.label_8.setText(_translate("PopDevWizard", "Which three countries fall into the \'very large", None))
        self.brazilPop.setText(_translate("PopDevWizard", "Brazil, Japan, Indonesia", None))
        self.label_9.setText(_translate("PopDevWizard", "population\' category?", None))
        self.label_10.setText(_translate("PopDevWizard", "Your Score:", None))
        self.ChangeColourButton_2.setText(_translate("PopDevWizard", "Colour", None))
        self.colourRampLabel_2.setText(_translate("PopDevWizard", "Colour Ramp:", None))
        self.StyleTypecomboBox_2.setItemText(0, _translate("PopDevWizard", "Single Colour", None))
        self.StyleTypecomboBox_2.setItemText(1, _translate("PopDevWizard", "Categorized", None))
        self.ColumncomboBox_2.setItemText(0, _translate("PopDevWizard", "economy", None))
        self.ColumncomboBox_2.setItemText(1, _translate("PopDevWizard", "income_grp", None))
        self.ColumncomboBox_2.setItemText(2, _translate("PopDevWizard", "pop_group", None))
        self.Score_label_4.setText(_translate("PopDevWizard", "0", None))
        self.textBrowser_4.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Use the options below to colour the map so that each </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">economy</span><span style=\" font-size:10pt;\"> is represented by a different colour, and click </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Next</span><span style=\" font-size:10pt;\">. </span></p></body></html>", None))
        self.columnLabel_2.setText(_translate("PopDevWizard", "Column:", None))
        self.label_11.setText(_translate("PopDevWizard", "Investigating Development", None))
        self.groupBox_3.setTitle(_translate("PopDevWizard", "3.", None))
        self.sAmerica.setText(_translate("PopDevWizard", "South America", None))
        self.asia.setText(_translate("PopDevWizard", "Asia", None))
        self.europe.setText(_translate("PopDevWizard", "Europe", None))
        self.label_12.setText(_translate("PopDevWizard", "Which continent holds the majority of the", None))
        self.africa.setText(_translate("PopDevWizard", "Africa", None))
        self.label_19.setText(_translate("PopDevWizard", "least developed countries?", None))
        self.groupBox_4.setTitle(_translate("PopDevWizard", "4.", None))
        self.tla.setText(_translate("PopDevWizard", "Tanzania, Libya, Algeria", None))
        self.imj.setText(_translate("PopDevWizard", "India, Mexico, Japan", None))
        self.spm.setText(_translate("PopDevWizard", "Spain, Poland, Moldova", None))
        self.label_13.setText(_translate("PopDevWizard", "Which three countries are part of the", None))
        self.ufi.setText(_translate("PopDevWizard", "UK, France, Italy", None))
        self.label_14.setText(_translate("PopDevWizard", "developed region: G7 group?", None))
        self.label_15.setText(_translate("PopDevWizard", "questions:", None))
        self.label_16.setText(_translate("PopDevWizard", "Look at the map and answer the following", None))
        self.label_17.setText(_translate("PopDevWizard", "Question Time", None))
        self.checkAnswersDev.setText(_translate("PopDevWizard", "Check my answers!", None))
        self.label_18.setText(_translate("PopDevWizard", "Your Score:", None))
        self.Score_label_5.setText(_translate("PopDevWizard", "0", None))
        self.IntrotextBrowser_2.setWhatsThis(_translate("PopDevWizard", "Population & Development Intro", None))
        self.IntrotextBrowser_2.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You are now going to add another layer from the World Health Organisation (WHO) that contains data for male and female obesity across the globe. We can then compare this to national income to see if there is a correlation or not.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Click the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Browse</span><span style=\" font-size:10pt;\"> button below and navigate to the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Population &amp; Development</span><span style=\" font-size:10pt;\"> data folder and choose </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">obesity.shp</span><span style=\" font-size:10pt;\">.</span></p></body></html>", None))
        self.AddObesityLayerButton.setText(_translate("PopDevWizard", "Add Obesity Layer", None))
        self.Score_label_6.setText(_translate("PopDevWizard", "0", None))
        self.textBrowser_5.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">When the obesity layer appears on the map canvas, click Next.</span></p></body></html>", None))
        self.label_20.setText(_translate("PopDevWizard", "Your Score:", None))
        self.obesityBrowseButton.setText(_translate("PopDevWizard", "Browse", None))
        self.label_21.setText(_translate("PopDevWizard", "Development and Health", None))
        self.groupBox_5.setTitle(_translate("PopDevWizard", "Countries", None))
        self.columnLabel_3.setText(_translate("PopDevWizard", "Column:", None))
        self.label_22.setText(_translate("PopDevWizard", "Your Score:", None))
        self.Score_label_7.setText(_translate("PopDevWizard", "0", None))
        self.groupBox_6.setTitle(_translate("PopDevWizard", "Obesity", None))
        self.columnLabel_4.setText(_translate("PopDevWizard", "Column:", None))
        self.colourRampLabel_3.setText(_translate("PopDevWizard", "Colour Ramp:", None))
        self.label_23.setText(_translate("PopDevWizard", "Comparing Colours", None))
        self.textBrowser_6.setHtml(_translate("PopDevWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Select</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> income_grp</span><span style=\" font-size:10pt;\"> for the countries column and </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">male_2010</span><span style=\" font-size:10pt;\"> for the obesity column, then click Next.</span></p></body></html>", None))
        self.countriesCheckBox.setText(_translate("PopDevWizard", "Countries", None))
        self.label_24.setText(_translate("PopDevWizard", "Looking for Correlations", None))
        self.label_25.setText(_translate("PopDevWizard", "Toggle the checkboxes below to turn the", None))
        self.label_26.setText(_translate("PopDevWizard", "loaded layers on and off. Look for similarities", None))
        self.label_27.setText(_translate("PopDevWizard", "and differences between income and obesity.", None))
        self.groupBox_7.setTitle(_translate("PopDevWizard", "5.", None))
        self.hihi.setText(_translate("PopDevWizard", "High income: non OECD, high obesity", None))
        self.vlovlo.setText(_translate("PopDevWizard", "Very low income, very low obesity", None))
        self.hivhi.setText(_translate("PopDevWizard", "High income: OECD, very high obesity", None))
        self.label_28.setText(_translate("PopDevWizard", "Look at the USA, what is the income and", None))
        self.hilo.setText(_translate("PopDevWizard", "High income: OECD, low obesity", None))
        self.label_29.setText(_translate("PopDevWizard", "obesity level of this country?", None))
        self.obesityCheckBox.setText(_translate("PopDevWizard", "Obesity", None))
        self.groupBox_8.setTitle(_translate("PopDevWizard", "6.", None))
        self.vLoOb.setText(_translate("PopDevWizard", "Low income, very low obesity", None))
        self.hiOb.setText(_translate("PopDevWizard", "High income: OECD, high obesity", None))
        self.hiOb_2.setText(_translate("PopDevWizard", "High income: nonOECD, high obesity", None))
        self.label_30.setText(_translate("PopDevWizard", "What is the general relationship between", None))
        self.midOb.setText(_translate("PopDevWizard", "Low income, medium obesity", None))
        self.label_31.setText(_translate("PopDevWizard", "obesity and income in central Africa?", None))
        self.Score_label_8.setText(_translate("PopDevWizard", "0", None))
        self.label_32.setText(_translate("PopDevWizard", "Your Score:", None))
        self.checkAnswersObs.setText(_translate("PopDevWizard", "Check my answers!", None))
        self.groupBox_9.setTitle(_translate("PopDevWizard", "6.", None))
        self.a.setText(_translate("PopDevWizard", "Density is the number of people in a given", None))
        self.c.setText(_translate("PopDevWizard", "Density is related to people\'s intelligence", None))
        self.b.setText(_translate("PopDevWizard", "Density is related to people\'s weight and", None))
        self.label_48.setText(_translate("PopDevWizard", "What is the difference between population", None))
        self.label_49.setText(_translate("PopDevWizard", "density and distribution?", None))
        self.label_33.setText(_translate("PopDevWizard", "area. Distribution is the way people are", None))
        self.label_34.setText(_translate("PopDevWizard", "spread across the earth.", None))
        self.label_37.setText(_translate("PopDevWizard", "distribution is related to giving aid to other", None))
        self.label_44.setText(_translate("PopDevWizard", "distribution is related to number of people", None))
        self.label_45.setText(_translate("PopDevWizard", "countries.", None))
        self.label_50.setText(_translate("PopDevWizard", "claiming benefits.", None))
        self.Score_label_9.setText(_translate("PopDevWizard", "0", None))
        self.label_35.setText(_translate("PopDevWizard", "Your Score:", None))
        self.label_36.setText(_translate("PopDevWizard", "Further Thoughts", None))
        self.label_38.setText(_translate("PopDevWizard", "It appears that income and obesity may be", None))
        self.label_39.setText(_translate("PopDevWizard", "related. Why do you think this might be?", None))
        self.label_40.setText(_translate("PopDevWizard", "Why do you think some areas are more", None))
        self.label_41.setText(_translate("PopDevWizard", "developed than others?", None))
        self.label_42.setText(_translate("PopDevWizard", "Why do some countries have a much higher", None))
        self.label_43.setText(_translate("PopDevWizard", "population than others?", None))
        self.checkAnswersPopDens.setText(_translate("PopDevWizard", "Check my answer!", None))
        self.label_46.setText(_translate("PopDevWizard", "Congratulations!", None))
        self.label_47.setText(_translate("PopDevWizard", "You have now completed Unit 1.", None))
        self.label_51.setText(_translate("PopDevWizard", "SCORE:", None))
        self.Score_label_10.setText(_translate("PopDevWizard", "0", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PopDevWizard = QtGui.QWizard()
    ui = Ui_PopDevWizard()
    ui.setupUi(PopDevWizard)
    PopDevWizard.show()
    sys.exit(app.exec_())

