# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charlottegraves\.qgis2\python\plugins\QGISforSchools\tourism_wizard.ui'
#
# Created: Wed Jul 02 18:42:08 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TourismWizard(object):
    def setupUi(self, TourismWizard):
        TourismWizard.setObjectName(_fromUtf8("TourismWizard"))
        TourismWizard.resize(292, 590)
        TourismWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        TourismWizard.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.IntrotextBrowser = QtGui.QTextBrowser(self.wizardPage1)
        self.IntrotextBrowser.setGeometry(QtCore.QRect(20, 20, 256, 501))
        self.IntrotextBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.IntrotextBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.IntrotextBrowser.setObjectName(_fromUtf8("IntrotextBrowser"))
        TourismWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.label_7 = QtGui.QLabel(self.wizardPage2)
        self.label_7.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Score_label = QtGui.QLabel(self.wizardPage2)
        self.Score_label.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label.setFont(font)
        self.Score_label.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label.setObjectName(_fromUtf8("Score_label"))
        self.label = QtGui.QLabel(self.wizardPage2)
        self.label.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 280, 271, 181))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.shopping = QtGui.QRadioButton(self.groupBox_2)
        self.shopping.setGeometry(QtCore.QRect(50, 120, 161, 21))
        self.shopping.setObjectName(_fromUtf8("shopping"))
        self.weather = QtGui.QRadioButton(self.groupBox_2)
        self.weather.setGeometry(QtCore.QRect(50, 100, 161, 21))
        self.weather.setObjectName(_fromUtf8("weather"))
        self.landscapes = QtGui.QRadioButton(self.groupBox_2)
        self.landscapes.setGeometry(QtCore.QRect(50, 140, 191, 21))
        self.landscapes.setObjectName(_fromUtf8("landscapes"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.art = QtGui.QRadioButton(self.groupBox_2)
        self.art.setGeometry(QtCore.QRect(50, 80, 161, 21))
        self.art.setObjectName(_fromUtf8("art"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 40, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.wizardPage2)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 40, 271, 131))
        self.textBrowser_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_3.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.groupBox_6 = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 150, 271, 111))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.AddWoodLayer = QtGui.QPushButton(self.groupBox_6)
        self.AddWoodLayer.setGeometry(QtCore.QRect(10, 70, 251, 21))
        self.AddWoodLayer.setObjectName(_fromUtf8("AddWoodLayer"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 251, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.woodLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.woodLineEdit.setObjectName(_fromUtf8("woodLineEdit"))
        self.horizontalLayout_2.addWidget(self.woodLineEdit)
        self.woodBrowseButton = QtGui.QPushButton(self.layoutWidget)
        self.woodBrowseButton.setObjectName(_fromUtf8("woodBrowseButton"))
        self.horizontalLayout_2.addWidget(self.woodBrowseButton)
        self.checkAnswersLand = QtGui.QPushButton(self.wizardPage2)
        self.checkAnswersLand.setGeometry(QtCore.QRect(20, 470, 251, 21))
        self.checkAnswersLand.setObjectName(_fromUtf8("checkAnswersLand"))
        TourismWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.label_8 = QtGui.QLabel(self.wizardPage3)
        self.label_8.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.wizardPage3)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 30, 271, 131))
        self.textBrowser_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_4.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.groupBox = QtGui.QGroupBox(self.wizardPage3)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 271, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.riverLineEdit = QtGui.QLineEdit(self.groupBox)
        self.riverLineEdit.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.riverLineEdit.setObjectName(_fromUtf8("riverLineEdit"))
        self.AddRiverLayer = QtGui.QPushButton(self.groupBox)
        self.AddRiverLayer.setGeometry(QtCore.QRect(10, 70, 251, 21))
        self.AddRiverLayer.setObjectName(_fromUtf8("AddRiverLayer"))
        self.riverBrowseButton = QtGui.QPushButton(self.groupBox)
        self.riverBrowseButton.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.riverBrowseButton.setObjectName(_fromUtf8("riverBrowseButton"))
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 340, 271, 161))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(10, 30, 85, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.riverColourButton = QtGui.QPushButton(self.groupBox_3)
        self.riverColourButton.setGeometry(QtCore.QRect(160, 30, 91, 21))
        self.riverColourButton.setObjectName(_fromUtf8("riverColourButton"))
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.lineStyle = QtGui.QComboBox(self.groupBox_3)
        self.lineStyle.setGeometry(QtCore.QRect(160, 90, 91, 21))
        self.lineStyle.setObjectName(_fromUtf8("lineStyle"))
        self.lineStyle.addItem(_fromUtf8(""))
        self.lineStyle.addItem(_fromUtf8(""))
        self.lineStyle.addItem(_fromUtf8(""))
        self.lineStyle.addItem(_fromUtf8(""))
        self.lineStyle.addItem(_fromUtf8(""))
        self.lineStyle.addItem(_fromUtf8(""))
        self.riverWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.riverWidth.setGeometry(QtCore.QRect(160, 60, 91, 22))
        self.riverWidth.setProperty("value", 1.0)
        self.riverWidth.setObjectName(_fromUtf8("riverWidth"))
        self.applyRiverStyle = QtGui.QPushButton(self.groupBox_3)
        self.applyRiverStyle.setGeometry(QtCore.QRect(50, 130, 161, 23))
        self.applyRiverStyle.setObjectName(_fromUtf8("applyRiverStyle"))
        self.groupBox_4 = QtGui.QGroupBox(self.wizardPage3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 160, 271, 51))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.woodColourButton = QtGui.QPushButton(self.groupBox_4)
        self.woodColourButton.setGeometry(QtCore.QRect(160, 20, 91, 21))
        self.woodColourButton.setObjectName(_fromUtf8("woodColourButton"))
        self.Score_label_2 = QtGui.QLabel(self.wizardPage3)
        self.Score_label_2.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_2.setFont(font)
        self.Score_label_2.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_2.setObjectName(_fromUtf8("Score_label_2"))
        self.label_4 = QtGui.QLabel(self.wizardPage3)
        self.label_4.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        TourismWizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.label_9 = QtGui.QLabel(self.wizardPage4)
        self.label_9.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textBrowser_5 = QtGui.QTextBrowser(self.wizardPage4)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 30, 271, 101))
        self.textBrowser_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_5.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 130, 271, 101))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.urbanLineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.urbanLineEdit.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.urbanLineEdit.setObjectName(_fromUtf8("urbanLineEdit"))
        self.AddUrbanLayer = QtGui.QPushButton(self.groupBox_5)
        self.AddUrbanLayer.setGeometry(QtCore.QRect(10, 60, 251, 21))
        self.AddUrbanLayer.setObjectName(_fromUtf8("AddUrbanLayer"))
        self.urbanBrowseButton = QtGui.QPushButton(self.groupBox_5)
        self.urbanBrowseButton.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.urbanBrowseButton.setObjectName(_fromUtf8("urbanBrowseButton"))
        self.groupBox_7 = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 240, 271, 61))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_33 = QtGui.QLabel(self.groupBox_7)
        self.label_33.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.urbanColourButton = QtGui.QPushButton(self.groupBox_7)
        self.urbanColourButton.setGeometry(QtCore.QRect(160, 30, 91, 21))
        self.urbanColourButton.setObjectName(_fromUtf8("urbanColourButton"))
        self.label_10 = QtGui.QLabel(self.wizardPage4)
        self.label_10.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Score_label_3 = QtGui.QLabel(self.wizardPage4)
        self.Score_label_3.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_3.setFont(font)
        self.Score_label_3.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_3.setObjectName(_fromUtf8("Score_label_3"))
        self.groupBox_8 = QtGui.QGroupBox(self.wizardPage4)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 310, 271, 161))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.jobs = QtGui.QRadioButton(self.groupBox_8)
        self.jobs.setGeometry(QtCore.QRect(20, 100, 201, 21))
        self.jobs.setObjectName(_fromUtf8("jobs"))
        self.services = QtGui.QRadioButton(self.groupBox_8)
        self.services.setGeometry(QtCore.QRect(20, 80, 211, 21))
        self.services.setObjectName(_fromUtf8("services"))
        self.environment = QtGui.QRadioButton(self.groupBox_8)
        self.environment.setGeometry(QtCore.QRect(20, 120, 231, 21))
        self.environment.setObjectName(_fromUtf8("environment"))
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.income = QtGui.QRadioButton(self.groupBox_8)
        self.income.setGeometry(QtCore.QRect(20, 60, 221, 21))
        self.income.setObjectName(_fromUtf8("income"))
        self.label_24 = QtGui.QLabel(self.groupBox_8)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.checkAnswersNeg = QtGui.QPushButton(self.wizardPage4)
        self.checkAnswersNeg.setGeometry(QtCore.QRect(20, 480, 251, 21))
        self.checkAnswersNeg.setObjectName(_fromUtf8("checkAnswersNeg"))
        TourismWizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName(_fromUtf8("wizardPage5"))
        self.label_11 = QtGui.QLabel(self.wizardPage5)
        self.label_11.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.textBrowser_6 = QtGui.QTextBrowser(self.wizardPage5)
        self.textBrowser_6.setGeometry(QtCore.QRect(10, 30, 271, 151))
        self.textBrowser_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_6.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.AddLayersButton = QtGui.QPushButton(self.wizardPage5)
        self.AddLayersButton.setGeometry(QtCore.QRect(20, 480, 251, 21))
        self.AddLayersButton.setObjectName(_fromUtf8("AddLayersButton"))
        self.label_13 = QtGui.QLabel(self.wizardPage5)
        self.label_13.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Score_label_4 = QtGui.QLabel(self.wizardPage5)
        self.Score_label_4.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_4.setFont(font)
        self.Score_label_4.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_4.setObjectName(_fromUtf8("Score_label_4"))
        self.layoutWidget1 = QtGui.QWidget(self.wizardPage5)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 180, 251, 291))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.railLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.railLineEdit.setObjectName(_fromUtf8("railLineEdit"))
        self.gridLayout.addWidget(self.railLineEdit, 1, 0, 1, 1)
        self.railBrowseButton = QtGui.QPushButton(self.layoutWidget1)
        self.railBrowseButton.setObjectName(_fromUtf8("railBrowseButton"))
        self.gridLayout.addWidget(self.railBrowseButton, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.railStationLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.railStationLineEdit.setObjectName(_fromUtf8("railStationLineEdit"))
        self.gridLayout.addWidget(self.railStationLineEdit, 3, 0, 1, 1)
        self.railStationBrowseButton = QtGui.QPushButton(self.layoutWidget1)
        self.railStationBrowseButton.setObjectName(_fromUtf8("railStationBrowseButton"))
        self.gridLayout.addWidget(self.railStationBrowseButton, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 4, 0, 1, 1)
        self.minorRdLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.minorRdLineEdit.setObjectName(_fromUtf8("minorRdLineEdit"))
        self.gridLayout.addWidget(self.minorRdLineEdit, 5, 0, 1, 1)
        self.minorRdBrowseButton = QtGui.QPushButton(self.layoutWidget1)
        self.minorRdBrowseButton.setObjectName(_fromUtf8("minorRdBrowseButton"))
        self.gridLayout.addWidget(self.minorRdBrowseButton, 5, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.bRoadsLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.bRoadsLineEdit.setObjectName(_fromUtf8("bRoadsLineEdit"))
        self.gridLayout.addWidget(self.bRoadsLineEdit, 7, 0, 1, 1)
        self.bRoadsBrowseButton = QtGui.QPushButton(self.layoutWidget1)
        self.bRoadsBrowseButton.setObjectName(_fromUtf8("bRoadsBrowseButton"))
        self.gridLayout.addWidget(self.bRoadsBrowseButton, 7, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 8, 0, 1, 1)
        self.priRoadsLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.priRoadsLineEdit.setObjectName(_fromUtf8("priRoadsLineEdit"))
        self.gridLayout.addWidget(self.priRoadsLineEdit, 9, 0, 1, 1)
        self.priRoadsBrowseButton = QtGui.QPushButton(self.layoutWidget1)
        self.priRoadsBrowseButton.setObjectName(_fromUtf8("priRoadsBrowseButton"))
        self.gridLayout.addWidget(self.priRoadsBrowseButton, 9, 1, 1, 1)
        TourismWizard.addPage(self.wizardPage5)
        self.wizardPage6 = QtGui.QWizardPage()
        self.wizardPage6.setObjectName(_fromUtf8("wizardPage6"))
        self.textBrowser_7 = QtGui.QTextBrowser(self.wizardPage6)
        self.textBrowser_7.setGeometry(QtCore.QRect(10, 40, 271, 81))
        self.textBrowser_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_7.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_7.setObjectName(_fromUtf8("textBrowser_7"))
        self.label_20 = QtGui.QLabel(self.wizardPage6)
        self.label_20.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.wizardPage6)
        self.label_21.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.Score_label_5 = QtGui.QLabel(self.wizardPage6)
        self.Score_label_5.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_5.setFont(font)
        self.Score_label_5.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_5.setObjectName(_fromUtf8("Score_label_5"))
        self.groupBox_9 = QtGui.QGroupBox(self.wizardPage6)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 140, 271, 191))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_34 = QtGui.QLabel(self.groupBox_9)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineColourButton = QtGui.QPushButton(self.groupBox_9)
        self.lineColourButton.setGeometry(QtCore.QRect(160, 70, 91, 21))
        self.lineColourButton.setObjectName(_fromUtf8("lineColourButton"))
        self.label_35 = QtGui.QLabel(self.groupBox_9)
        self.label_35.setGeometry(QtCore.QRect(10, 100, 101, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.groupBox_9)
        self.label_36.setGeometry(QtCore.QRect(10, 130, 101, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.styleComboBox = QtGui.QComboBox(self.groupBox_9)
        self.styleComboBox.setGeometry(QtCore.QRect(160, 130, 91, 21))
        self.styleComboBox.setObjectName(_fromUtf8("styleComboBox"))
        self.styleComboBox.addItem(_fromUtf8(""))
        self.styleComboBox.addItem(_fromUtf8(""))
        self.styleComboBox.addItem(_fromUtf8(""))
        self.styleComboBox.addItem(_fromUtf8(""))
        self.styleComboBox.addItem(_fromUtf8(""))
        self.styleComboBox.addItem(_fromUtf8(""))
        self.lineWidth = QtGui.QDoubleSpinBox(self.groupBox_9)
        self.lineWidth.setGeometry(QtCore.QRect(160, 100, 91, 22))
        self.lineWidth.setProperty("value", 1.0)
        self.lineWidth.setObjectName(_fromUtf8("lineWidth"))
        self.lineLyrComboBox = QtGui.QComboBox(self.groupBox_9)
        self.lineLyrComboBox.setGeometry(QtCore.QRect(100, 30, 151, 22))
        self.lineLyrComboBox.setObjectName(_fromUtf8("lineLyrComboBox"))
        self.label_37 = QtGui.QLabel(self.groupBox_9)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 41, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.applyStyle = QtGui.QPushButton(self.groupBox_9)
        self.applyStyle.setGeometry(QtCore.QRect(50, 160, 161, 23))
        self.applyStyle.setObjectName(_fromUtf8("applyStyle"))
        self.groupBox_10 = QtGui.QGroupBox(self.wizardPage6)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 350, 271, 151))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_42 = QtGui.QLabel(self.groupBox_10)
        self.label_42.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.stationColour = QtGui.QPushButton(self.groupBox_10)
        self.stationColour.setGeometry(QtCore.QRect(160, 50, 91, 21))
        self.stationColour.setObjectName(_fromUtf8("stationColour"))
        self.addLabels = QtGui.QCheckBox(self.groupBox_10)
        self.addLabels.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.addLabels.setObjectName(_fromUtf8("addLabels"))
        self.labelFormat = QtGui.QPushButton(self.groupBox_10)
        self.labelFormat.setEnabled(False)
        self.labelFormat.setGeometry(QtCore.QRect(160, 20, 91, 23))
        self.labelFormat.setObjectName(_fromUtf8("labelFormat"))
        self.label_43 = QtGui.QLabel(self.groupBox_10)
        self.label_43.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.stationSize = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.stationSize.setGeometry(QtCore.QRect(160, 80, 91, 22))
        self.stationSize.setProperty("value", 2.0)
        self.stationSize.setObjectName(_fromUtf8("stationSize"))
        self.applyStationStyle = QtGui.QPushButton(self.groupBox_10)
        self.applyStationStyle.setGeometry(QtCore.QRect(50, 120, 161, 23))
        self.applyStationStyle.setObjectName(_fromUtf8("applyStationStyle"))
        TourismWizard.addPage(self.wizardPage6)
        self.wizardPage7 = QtGui.QWizardPage()
        self.wizardPage7.setObjectName(_fromUtf8("wizardPage7"))
        self.textBrowser_8 = QtGui.QTextBrowser(self.wizardPage7)
        self.textBrowser_8.setGeometry(QtCore.QRect(10, 40, 271, 141))
        self.textBrowser_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_8.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_8.setObjectName(_fromUtf8("textBrowser_8"))
        self.label_22 = QtGui.QLabel(self.wizardPage7)
        self.label_22.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.groupBox_11 = QtGui.QGroupBox(self.wizardPage7)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 300, 271, 171))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.landOwners = QtGui.QRadioButton(self.groupBox_11)
        self.landOwners.setGeometry(QtCore.QRect(20, 110, 201, 21))
        self.landOwners.setObjectName(_fromUtf8("landOwners"))
        self.dollar = QtGui.QRadioButton(self.groupBox_11)
        self.dollar.setGeometry(QtCore.QRect(20, 70, 251, 21))
        self.dollar.setObjectName(_fromUtf8("dollar"))
        self.envImpact = QtGui.QRadioButton(self.groupBox_11)
        self.envImpact.setGeometry(QtCore.QRect(20, 130, 231, 21))
        self.envImpact.setObjectName(_fromUtf8("envImpact"))
        self.label_27 = QtGui.QLabel(self.groupBox_11)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.balance = QtGui.QRadioButton(self.groupBox_11)
        self.balance.setGeometry(QtCore.QRect(20, 40, 241, 21))
        self.balance.setObjectName(_fromUtf8("balance"))
        self.label_2 = QtGui.QLabel(self.groupBox_11)
        self.label_2.setGeometry(QtCore.QRect(40, 53, 171, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_28 = QtGui.QLabel(self.groupBox_11)
        self.label_28.setGeometry(QtCore.QRect(40, 90, 141, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_45 = QtGui.QLabel(self.groupBox_11)
        self.label_45.setGeometry(QtCore.QRect(40, 150, 201, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.Score_label_6 = QtGui.QLabel(self.wizardPage7)
        self.Score_label_6.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_6.setFont(font)
        self.Score_label_6.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_6.setObjectName(_fromUtf8("Score_label_6"))
        self.label_44 = QtGui.QLabel(self.wizardPage7)
        self.label_44.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.checkAnswersSust = QtGui.QPushButton(self.wizardPage7)
        self.checkAnswersSust.setGeometry(QtCore.QRect(20, 480, 251, 21))
        self.checkAnswersSust.setObjectName(_fromUtf8("checkAnswersSust"))
        self.groupBox_13 = QtGui.QGroupBox(self.wizardPage7)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 180, 271, 81))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.settlementLineEdit = QtGui.QLineEdit(self.groupBox_13)
        self.settlementLineEdit.setGeometry(QtCore.QRect(10, 20, 171, 20))
        self.settlementLineEdit.setObjectName(_fromUtf8("settlementLineEdit"))
        self.AddSettlementLayer = QtGui.QPushButton(self.groupBox_13)
        self.AddSettlementLayer.setGeometry(QtCore.QRect(10, 50, 251, 21))
        self.AddSettlementLayer.setObjectName(_fromUtf8("AddSettlementLayer"))
        self.settlementBrowseButton = QtGui.QPushButton(self.groupBox_13)
        self.settlementBrowseButton.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.settlementBrowseButton.setObjectName(_fromUtf8("settlementBrowseButton"))
        self.layoutWidget2 = QtGui.QWidget(self.wizardPage7)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 270, 251, 25))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_25 = QtGui.QLabel(self.layoutWidget2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout.addWidget(self.label_25)
        self.formatLabels = QtGui.QPushButton(self.layoutWidget2)
        self.formatLabels.setObjectName(_fromUtf8("formatLabels"))
        self.horizontalLayout.addWidget(self.formatLabels)
        TourismWizard.addPage(self.wizardPage7)
        self.wizardPage8 = QtGui.QWizardPage()
        self.wizardPage8.setObjectName(_fromUtf8("wizardPage8"))
        self.label_46 = QtGui.QLabel(self.wizardPage8)
        self.label_46.setGeometry(QtCore.QRect(150, 508, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.Score_label_7 = QtGui.QLabel(self.wizardPage8)
        self.Score_label_7.setGeometry(QtCore.QRect(230, 510, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_7.setFont(font)
        self.Score_label_7.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_7.setObjectName(_fromUtf8("Score_label_7"))
        self.label_47 = QtGui.QLabel(self.wizardPage8)
        self.label_47.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.textBrowser_9 = QtGui.QTextBrowser(self.wizardPage8)
        self.textBrowser_9.setGeometry(QtCore.QRect(10, 40, 271, 191))
        self.textBrowser_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_9.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_9.setObjectName(_fromUtf8("textBrowser_9"))
        self.groupBox_12 = QtGui.QGroupBox(self.wizardPage8)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 160, 271, 111))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.attractionLineEdit = QtGui.QLineEdit(self.groupBox_12)
        self.attractionLineEdit.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.attractionLineEdit.setObjectName(_fromUtf8("attractionLineEdit"))
        self.AddAttractionLayer = QtGui.QPushButton(self.groupBox_12)
        self.AddAttractionLayer.setGeometry(QtCore.QRect(10, 70, 251, 21))
        self.AddAttractionLayer.setObjectName(_fromUtf8("AddAttractionLayer"))
        self.attractionBrowseButton = QtGui.QPushButton(self.groupBox_12)
        self.attractionBrowseButton.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.attractionBrowseButton.setObjectName(_fromUtf8("attractionBrowseButton"))
        self.groupBox_14 = QtGui.QGroupBox(self.wizardPage8)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 280, 271, 181))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.sustainable = QtGui.QRadioButton(self.groupBox_14)
        self.sustainable.setGeometry(QtCore.QRect(20, 110, 201, 21))
        self.sustainable.setObjectName(_fromUtf8("sustainable"))
        self.disrespect = QtGui.QRadioButton(self.groupBox_14)
        self.disrespect.setGeometry(QtCore.QRect(20, 70, 251, 21))
        self.disrespect.setObjectName(_fromUtf8("disrespect"))
        self.Mass = QtGui.QRadioButton(self.groupBox_14)
        self.Mass.setGeometry(QtCore.QRect(20, 150, 231, 21))
        self.Mass.setObjectName(_fromUtf8("Mass"))
        self.label_48 = QtGui.QLabel(self.groupBox_14)
        self.label_48.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.hiImpact = QtGui.QRadioButton(self.groupBox_14)
        self.hiImpact.setGeometry(QtCore.QRect(20, 40, 241, 21))
        self.hiImpact.setObjectName(_fromUtf8("hiImpact"))
        self.label_49 = QtGui.QLabel(self.groupBox_14)
        self.label_49.setGeometry(QtCore.QRect(40, 90, 141, 16))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.groupBox_14)
        self.label_50.setGeometry(QtCore.QRect(40, 130, 201, 16))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.checkAnswersEco = QtGui.QPushButton(self.wizardPage8)
        self.checkAnswersEco.setGeometry(QtCore.QRect(20, 470, 251, 21))
        self.checkAnswersEco.setObjectName(_fromUtf8("checkAnswersEco"))
        TourismWizard.addPage(self.wizardPage8)
        self.wizardPage9 = QtGui.QWizardPage()
        self.wizardPage9.setObjectName(_fromUtf8("wizardPage9"))
        self.Score_label_8 = QtGui.QLabel(self.wizardPage9)
        self.Score_label_8.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_8.setFont(font)
        self.Score_label_8.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_8.setObjectName(_fromUtf8("Score_label_8"))
        self.label_51 = QtGui.QLabel(self.wizardPage9)
        self.label_51.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.textBrowser_10 = QtGui.QTextBrowser(self.wizardPage9)
        self.textBrowser_10.setGeometry(QtCore.QRect(10, 40, 271, 91))
        self.textBrowser_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_10.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_10.setObjectName(_fromUtf8("textBrowser_10"))
        self.label_52 = QtGui.QLabel(self.wizardPage9)
        self.label_52.setGeometry(QtCore.QRect(70, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.AttractionTableView = QtGui.QTableView(self.wizardPage9)
        self.AttractionTableView.setGeometry(QtCore.QRect(20, 210, 256, 281))
        self.AttractionTableView.setObjectName(_fromUtf8("AttractionTableView"))
        self.fieldComboBox = QtGui.QComboBox(self.wizardPage9)
        self.fieldComboBox.setGeometry(QtCore.QRect(20, 160, 131, 21))
        self.fieldComboBox.setObjectName(_fromUtf8("fieldComboBox"))
        self.getIcons = QtGui.QPushButton(self.wizardPage9)
        self.getIcons.setGeometry(QtCore.QRect(170, 160, 101, 23))
        self.getIcons.setObjectName(_fromUtf8("getIcons"))
        self.label_5 = QtGui.QLabel(self.wizardPage9)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_26 = QtGui.QLabel(self.wizardPage9)
        self.label_26.setGeometry(QtCore.QRect(20, 190, 91, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        TourismWizard.addPage(self.wizardPage9)
        self.wizardPage10 = QtGui.QWizardPage()
        self.wizardPage10.setObjectName(_fromUtf8("wizardPage10"))
        self.label_53 = QtGui.QLabel(self.wizardPage10)
        self.label_53.setGeometry(QtCore.QRect(70, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.checkAnswersAccom = QtGui.QPushButton(self.wizardPage10)
        self.checkAnswersAccom.setGeometry(QtCore.QRect(20, 440, 251, 21))
        self.checkAnswersAccom.setObjectName(_fromUtf8("checkAnswersAccom"))
        self.groupBox_15 = QtGui.QGroupBox(self.wizardPage10)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 270, 271, 161))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.selfCat = QtGui.QRadioButton(self.groupBox_15)
        self.selfCat.setGeometry(QtCore.QRect(60, 130, 161, 21))
        self.selfCat.setObjectName(_fromUtf8("selfCat"))
        self.camp = QtGui.QRadioButton(self.groupBox_15)
        self.camp.setGeometry(QtCore.QRect(60, 70, 161, 21))
        self.camp.setObjectName(_fromUtf8("camp"))
        self.bnb = QtGui.QRadioButton(self.groupBox_15)
        self.bnb.setGeometry(QtCore.QRect(60, 110, 161, 21))
        self.bnb.setObjectName(_fromUtf8("bnb"))
        self.label_54 = QtGui.QLabel(self.groupBox_15)
        self.label_54.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.hotel = QtGui.QRadioButton(self.groupBox_15)
        self.hotel.setGeometry(QtCore.QRect(60, 90, 161, 21))
        self.hotel.setObjectName(_fromUtf8("hotel"))
        self.label_55 = QtGui.QLabel(self.groupBox_15)
        self.label_55.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.wizardPage10)
        self.label_56.setGeometry(QtCore.QRect(20, 50, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.groupBox_16 = QtGui.QGroupBox(self.wizardPage10)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 110, 271, 151))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.railway = QtGui.QRadioButton(self.groupBox_16)
        self.railway.setGeometry(QtCore.QRect(50, 100, 161, 21))
        self.railway.setObjectName(_fromUtf8("railway"))
        self.nature = QtGui.QRadioButton(self.groupBox_16)
        self.nature.setGeometry(QtCore.QRect(50, 80, 161, 21))
        self.nature.setObjectName(_fromUtf8("nature"))
        self.monument = QtGui.QRadioButton(self.groupBox_16)
        self.monument.setGeometry(QtCore.QRect(50, 120, 161, 21))
        self.monument.setObjectName(_fromUtf8("monument"))
        self.label_57 = QtGui.QLabel(self.groupBox_16)
        self.label_57.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.karting = QtGui.QRadioButton(self.groupBox_16)
        self.karting.setGeometry(QtCore.QRect(50, 60, 161, 21))
        self.karting.setObjectName(_fromUtf8("karting"))
        self.label_60 = QtGui.QLabel(self.groupBox_16)
        self.label_60.setGeometry(QtCore.QRect(10, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_58 = QtGui.QLabel(self.wizardPage10)
        self.label_58.setGeometry(QtCore.QRect(20, 70, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.wizardPage10)
        self.label_59.setGeometry(QtCore.QRect(150, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.Score_label_9 = QtGui.QLabel(self.wizardPage10)
        self.Score_label_9.setGeometry(QtCore.QRect(230, 512, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Score_label_9.setFont(font)
        self.Score_label_9.setFrameShape(QtGui.QFrame.Panel)
        self.Score_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_9.setObjectName(_fromUtf8("Score_label_9"))
        self.label_61 = QtGui.QLabel(self.wizardPage10)
        self.label_61.setGeometry(QtCore.QRect(10, 460, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.wizardPage10)
        self.label_62.setGeometry(QtCore.QRect(10, 480, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        TourismWizard.addPage(self.wizardPage10)
        self.wizardPage11 = QtGui.QWizardPage()
        self.wizardPage11.setObjectName(_fromUtf8("wizardPage11"))
        self.label_63 = QtGui.QLabel(self.wizardPage11)
        self.label_63.setGeometry(QtCore.QRect(30, 30, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.starView = QtGui.QGraphicsView(self.wizardPage11)
        self.starView.setGeometry(QtCore.QRect(20, 270, 256, 192))
        self.starView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.starView.setFrameShadow(QtGui.QFrame.Sunken)
        self.starView.setObjectName(_fromUtf8("starView"))
        self.label_64 = QtGui.QLabel(self.wizardPage11)
        self.label_64.setGeometry(QtCore.QRect(50, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Levenim MT"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.Score_label_10 = QtGui.QLabel(self.wizardPage11)
        self.Score_label_10.setGeometry(QtCore.QRect(100, 150, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.Score_label_10.setFont(font)
        self.Score_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_label_10.setObjectName(_fromUtf8("Score_label_10"))
        self.label_65 = QtGui.QLabel(self.wizardPage11)
        self.label_65.setGeometry(QtCore.QRect(30, 60, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        TourismWizard.addPage(self.wizardPage11)

        self.retranslateUi(TourismWizard)
        QtCore.QObject.connect(self.addLabels, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelFormat.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TourismWizard)

    def retranslateUi(self, TourismWizard):
        TourismWizard.setWindowTitle(_translate("TourismWizard", "Tourist Maps", None))
        self.IntrotextBrowser.setWhatsThis(_translate("TourismWizard", "Population & Development Intro", None))
        self.IntrotextBrowser.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">Unit 2</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Tourism</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Tourism is a very large global industry which generates both income and jobs. There can, however, be significant negative effects of tourism on the local people and environment if it is not carefully controlled.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Aviemore is a popular tourist destination in the Cairngorm National Park, Scotland. There are snowsports facilities, walking, climbing, biking and many attractions in the area. For this unit, imagine that you have been employed by Aviemore Tourist Information Office to create a tourist map of the area. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Tip: When choosing styles and colours for layers, it might be useful to consult an Ordnance Survey map.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You will be asked questions as you go. You will earn </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">5</span><span style=\" font-size:10pt;\"> points for getting the answer right first time, </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">3</span><span style=\" font-size:10pt;\"> for getting it right second time and </span><span style=\" font-size:10pt; font-weight:600; color:#aa007f;\">1</span><span style=\" font-size:10pt;\"> for getting it right any time thereafter.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.label_7.setText(_translate("TourismWizard", "Adding Layers", None))
        self.Score_label.setText(_translate("TourismWizard", "0", None))
        self.label.setText(_translate("TourismWizard", "Your Score:", None))
        self.groupBox_2.setTitle(_translate("TourismWizard", "1.", None))
        self.shopping.setText(_translate("TourismWizard", "To go shopping", None))
        self.weather.setText(_translate("TourismWizard", "To enjoy the great weather", None))
        self.landscapes.setText(_translate("TourismWizard", "To enjoy the beautiful landscapes", None))
        self.label_18.setText(_translate("TourismWizard", "Why are tourists most likely to visit a UK", None))
        self.art.setText(_translate("TourismWizard", "To visit art galleries", None))
        self.label_23.setText(_translate("TourismWizard", "national park like the Cairngorms?", None))
        self.textBrowser_3.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You will build your map up one layer at a time to keep it neat and well-structured. Firstly we will add a natural layer for some context. Navigate to the Tourism folder using the </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">Browse</span><span style=\" font-size:10pt;\"> button below and select </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">woodland.shp</span><span style=\" font-size:10pt;\">.</span></p></body></html>", None))
        self.groupBox_6.setTitle(_translate("TourismWizard", "Add woodland.shp", None))
        self.AddWoodLayer.setText(_translate("TourismWizard", "Add Layer!", None))
        self.woodBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.checkAnswersLand.setText(_translate("TourismWizard", "Check my answer!", None))
        self.label_8.setText(_translate("TourismWizard", "Re-Styling Layers", None))
        self.textBrowser_4.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Purple is not a colour that is naturally associated with woodlands. To make your map easier to understand, use the colour section below to change it to a more suitable colour. Then add rivers.shp to the map by using the Browse button below and restyle that layer so that it clearly represents rivers.</span></p></body></html>", None))
        self.groupBox.setTitle(_translate("TourismWizard", "Add rivers.shp", None))
        self.AddRiverLayer.setText(_translate("TourismWizard", "Add Layer!", None))
        self.riverBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.groupBox_3.setTitle(_translate("TourismWizard", "Re-style Rivers", None))
        self.label_30.setText(_translate("TourismWizard", "Set river colour:", None))
        self.riverColourButton.setText(_translate("TourismWizard", "Colour", None))
        self.label_31.setText(_translate("TourismWizard", "Set line width:", None))
        self.label_32.setText(_translate("TourismWizard", "Set line style:", None))
        self.lineStyle.setItemText(0, _translate("TourismWizard", "Solid Line", None))
        self.lineStyle.setItemText(1, _translate("TourismWizard", "No Pen", None))
        self.lineStyle.setItemText(2, _translate("TourismWizard", "Dash Line", None))
        self.lineStyle.setItemText(3, _translate("TourismWizard", "Dot Line", None))
        self.lineStyle.setItemText(4, _translate("TourismWizard", "Dash Dot Line", None))
        self.lineStyle.setItemText(5, _translate("TourismWizard", "Dash Dot Dot Line", None))
        self.applyRiverStyle.setText(_translate("TourismWizard", "Apply Style", None))
        self.groupBox_4.setTitle(_translate("TourismWizard", "Re-style Woodland", None))
        self.label_29.setText(_translate("TourismWizard", "Set woodland colour:", None))
        self.woodColourButton.setText(_translate("TourismWizard", "Colour", None))
        self.Score_label_2.setText(_translate("TourismWizard", "0", None))
        self.label_4.setText(_translate("TourismWizard", "Your Score:", None))
        self.label_9.setText(_translate("TourismWizard", "Anthropogenic Layers", None))
        self.textBrowser_5.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Now that we have added woodland and rivers to give the natural context, we can add some layers representing man-made features. Use the</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> Browse</span><span style=\" font-size:10pt;\"> button below to select the</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> buildings.shp</span><span style=\" font-size:10pt;\"> file, then re-style it.</span></p></body></html>", None))
        self.groupBox_5.setTitle(_translate("TourismWizard", "Add buildings.shp", None))
        self.AddUrbanLayer.setText(_translate("TourismWizard", "Add Layer!", None))
        self.urbanBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.groupBox_7.setTitle(_translate("TourismWizard", "Re-style buildings", None))
        self.label_33.setText(_translate("TourismWizard", "Set buildings colour:", None))
        self.urbanColourButton.setText(_translate("TourismWizard", "Colour", None))
        self.label_10.setText(_translate("TourismWizard", "Your Score:", None))
        self.Score_label_3.setText(_translate("TourismWizard", "0", None))
        self.groupBox_8.setTitle(_translate("TourismWizard", "2.", None))
        self.jobs.setText(_translate("TourismWizard", "More jobs generated by tourism", None))
        self.services.setText(_translate("TourismWizard", "More services provided in local areas", None))
        self.environment.setText(_translate("TourismWizard", "Damage to the natural environment", None))
        self.label_19.setText(_translate("TourismWizard", "What can be a negative effect of increased", None))
        self.income.setText(_translate("TourismWizard", "Increased income for local businesses", None))
        self.label_24.setText(_translate("TourismWizard", "tourism in national parks?", None))
        self.checkAnswersNeg.setText(_translate("TourismWizard", "Check my answer!", None))
        self.label_11.setText(_translate("TourismWizard", "Transport Layers", None))
        self.textBrowser_6.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">It is important to make transportation features such as roads and rail stations very clear as tourists will require this information to get to Aviemore and its attractions. Use the functionality provided blow to add</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> railway_line.shp</span><span style=\" font-size:10pt;\">, </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">railway_station.shp</span><span style=\" font-size:10pt;\">, </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">minor_road.shp</span><span style=\" font-size:10pt;\">,</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> b_road.shp</span><span style=\" font-size:10pt;\"> and </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">primary_road.shp</span><span style=\" font-size:10pt;\">.</span></p></body></html>", None))
        self.AddLayersButton.setText(_translate("TourismWizard", "Add Layers!", None))
        self.label_13.setText(_translate("TourismWizard", "Your Score:", None))
        self.Score_label_4.setText(_translate("TourismWizard", "0", None))
        self.label_12.setText(_translate("TourismWizard", "Add the railway line layer:", None))
        self.railBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.label_14.setText(_translate("TourismWizard", "Add the railway station layer:", None))
        self.railStationBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.label_15.setText(_translate("TourismWizard", "Add the minor roads layer:", None))
        self.minorRdBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.label_16.setText(_translate("TourismWizard", "Add the b roads layer:", None))
        self.bRoadsBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.label_17.setText(_translate("TourismWizard", "Add the primary roads layer:", None))
        self.priRoadsBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.textBrowser_7.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You can use colour, size and symbols to avoid confusing one layer for another. Use the functionality below to re-style the road, railways and railway station.</span></p></body></html>", None))
        self.label_20.setText(_translate("TourismWizard", "Differentiating", None))
        self.label_21.setText(_translate("TourismWizard", "Your Score:", None))
        self.Score_label_5.setText(_translate("TourismWizard", "0", None))
        self.groupBox_9.setTitle(_translate("TourismWizard", "Re-style Line Layers", None))
        self.label_34.setText(_translate("TourismWizard", "Set line colour:", None))
        self.lineColourButton.setText(_translate("TourismWizard", "Colour", None))
        self.label_35.setText(_translate("TourismWizard", "Set line width:", None))
        self.label_36.setText(_translate("TourismWizard", "Set line style:", None))
        self.styleComboBox.setItemText(0, _translate("TourismWizard", "Solid Line", None))
        self.styleComboBox.setItemText(1, _translate("TourismWizard", "No Pen", None))
        self.styleComboBox.setItemText(2, _translate("TourismWizard", "Dash Line", None))
        self.styleComboBox.setItemText(3, _translate("TourismWizard", "Dot Line", None))
        self.styleComboBox.setItemText(4, _translate("TourismWizard", "Dash Dot Line", None))
        self.styleComboBox.setItemText(5, _translate("TourismWizard", "Dash Dot Dot Line", None))
        self.label_37.setText(_translate("TourismWizard", "Layer:", None))
        self.applyStyle.setText(_translate("TourismWizard", "Apply Style", None))
        self.groupBox_10.setTitle(_translate("TourismWizard", "Re-style Rail Stations", None))
        self.label_42.setText(_translate("TourismWizard", "Set point colour:", None))
        self.stationColour.setText(_translate("TourismWizard", "Colour", None))
        self.addLabels.setText(_translate("TourismWizard", "Add labels", None))
        self.labelFormat.setText(_translate("TourismWizard", "Label format", None))
        self.label_43.setText(_translate("TourismWizard", "Set point size:", None))
        self.applyStationStyle.setText(_translate("TourismWizard", "Apply Style", None))
        self.textBrowser_8.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Text can be a very important addition to your map, as it is often the only way to communicate the name of a place or feature. With this in mind we can add a </span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">settlement_names.shp</span><span style=\" font-size:10pt;\"> layer using the browse button below. You can change the font, size and format of the text to make it stand out too.</span></p></body></html>", None))
        self.label_22.setText(_translate("TourismWizard", "Labelling", None))
        self.groupBox_11.setTitle(_translate("TourismWizard", "3.", None))
        self.landOwners.setText(_translate("TourismWizard", "Ignoring impacts on local land owners", None))
        self.dollar.setText(_translate("TourismWizard", "By making as much money as possible, without", None))
        self.envImpact.setText(_translate("TourismWizard", "Only consider the environmental impact and", None))
        self.label_27.setText(_translate("TourismWizard", "How can sustainable tourism be achieved?", None))
        self.balance.setText(_translate("TourismWizard", "By balancing the impacts on local people,", None))
        self.label_2.setText(_translate("TourismWizard", "the economy and the environment", None))
        self.label_28.setText(_translate("TourismWizard", "considering other impacts", None))
        self.label_45.setText(_translate("TourismWizard", "ignoring the impacts on local people", None))
        self.Score_label_6.setText(_translate("TourismWizard", "0", None))
        self.label_44.setText(_translate("TourismWizard", "Your Score:", None))
        self.checkAnswersSust.setText(_translate("TourismWizard", "Check my answer!", None))
        self.groupBox_13.setTitle(_translate("TourismWizard", "Add settlement_names.shp", None))
        self.AddSettlementLayer.setText(_translate("TourismWizard", "Add Layer!", None))
        self.settlementBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.label_25.setText(_translate("TourismWizard", "Style Labels:", None))
        self.formatLabels.setText(_translate("TourismWizard", "Format Labels", None))
        self.label_46.setText(_translate("TourismWizard", "Your Score:", None))
        self.Score_label_7.setText(_translate("TourismWizard", "0", None))
        self.label_47.setText(_translate("TourismWizard", "Tourist Attractions!", None))
        self.textBrowser_9.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Now you have created a good basemap with contextual information such as rivers and roads, we can finally add the most important layer - tourist attractions! Use the Browse button below to add</span><span style=\" font-size:10pt; font-weight:600; color:#00007f;\"> tourist_attraction.shp</span><span style=\" font-size:10pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>", None))
        self.groupBox_12.setTitle(_translate("TourismWizard", "Add tourist_attraction.shp", None))
        self.AddAttractionLayer.setText(_translate("TourismWizard", "Add Layer!", None))
        self.attractionBrowseButton.setText(_translate("TourismWizard", "Browse", None))
        self.groupBox_14.setTitle(_translate("TourismWizard", "4.", None))
        self.sustainable.setText(_translate("TourismWizard", "Low-impact, environmentally friendly,", None))
        self.disrespect.setText(_translate("TourismWizard", "Tourism that is disrespectful to local customs", None))
        self.Mass.setText(_translate("TourismWizard", "Mass tourism", None))
        self.label_48.setText(_translate("TourismWizard", "What is Eco-tourism?", None))
        self.hiImpact.setText(_translate("TourismWizard", "High impact, environmentally damaging tourism", None))
        self.label_49.setText(_translate("TourismWizard", "and traditions", None))
        self.label_50.setText(_translate("TourismWizard", "sustainable tourism", None))
        self.checkAnswersEco.setText(_translate("TourismWizard", "Check my answer!", None))
        self.Score_label_8.setText(_translate("TourismWizard", "0", None))
        self.label_51.setText(_translate("TourismWizard", "Your Score:", None))
        self.textBrowser_10.setHtml(_translate("TourismWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">To make different kinds of tourist attraction clear on your map, you can style each with a different icon. Use the functionality below to pick icons that best represent each attraction type.</span></p></body></html>", None))
        self.label_52.setText(_translate("TourismWizard", "Symbology", None))
        self.getIcons.setText(_translate("TourismWizard", "Get Icons", None))
        self.label_5.setText(_translate("TourismWizard", "Attraction Type:", None))
        self.label_26.setText(_translate("TourismWizard", "Layer symbology:", None))
        self.label_53.setText(_translate("TourismWizard", "Question Time", None))
        self.checkAnswersAccom.setText(_translate("TourismWizard", "Check my answers!", None))
        self.groupBox_15.setTitle(_translate("TourismWizard", "6.", None))
        self.selfCat.setText(_translate("TourismWizard", "Self-catering accommodation", None))
        self.camp.setText(_translate("TourismWizard", "Camping and caravan sites", None))
        self.bnb.setText(_translate("TourismWizard", "Bed && Breakfasts", None))
        self.label_54.setText(_translate("TourismWizard", "What kind of accommodation is represented", None))
        self.hotel.setText(_translate("TourismWizard", "Hotels", None))
        self.label_55.setText(_translate("TourismWizard", "on the map?", None))
        self.label_56.setText(_translate("TourismWizard", "Look at the map and answer the following", None))
        self.groupBox_16.setTitle(_translate("TourismWizard", "5.", None))
        self.railway.setText(_translate("TourismWizard", "Preserved Railway", None))
        self.nature.setText(_translate("TourismWizard", "Nature Reserve", None))
        self.monument.setText(_translate("TourismWizard", "Monument", None))
        self.label_57.setText(_translate("TourismWizard", "Which of the following provides a natural", None))
        self.karting.setText(_translate("TourismWizard", "Motor Racing Circuit", None))
        self.label_60.setText(_translate("TourismWizard", "resource as the attraction?", None))
        self.label_58.setText(_translate("TourismWizard", "questions:", None))
        self.label_59.setText(_translate("TourismWizard", "Your Score:", None))
        self.Score_label_9.setText(_translate("TourismWizard", "0", None))
        self.label_61.setText(_translate("TourismWizard", "Do you think your tourist map should have", None))
        self.label_62.setText(_translate("TourismWizard", "more information on it? What would you add?", None))
        self.label_63.setText(_translate("TourismWizard", "Congratulations!", None))
        self.label_64.setText(_translate("TourismWizard", "SCORE:", None))
        self.Score_label_10.setText(_translate("TourismWizard", "0", None))
        self.label_65.setText(_translate("TourismWizard", "You have now completed Unit 2.", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TourismWizard = QtGui.QWizard()
    ui = Ui_TourismWizard()
    ui.setupUi(TourismWizard)
    TourismWizard.show()
    sys.exit(app.exec_())

